apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: default

# nameSuffix: -v0-0-1

labels:
- includeSelectors: true
  pairs:
    version: v0.0.1

replicas:
- count: 1
  name: golang-api-server

configMapGenerator:
- behavior: merge
  envs:
  - tracing.env
  literals:
  - DEPLOY_ENV=prod
  name: golang-api-server

# https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable
generatorOptions:
  immutable: true

resources:
- ../../base
- ingress.yaml
- ingress-canary.yaml

patches:
- path: pathch-ingress-name.yaml
  target:
    kind: Ingress
    name: golang-api-server
    version: v1
- patch: |-
    - op: replace
      path: /metadata/name
      value: golang-api-server-canary
  target:
    kind: Ingress
    name: golang-api-server-canary
    version: v1
- path: patch_healthcheck.yaml
- path: patch_strategy.yaml
- path: patch_mem_cpu_resources.yaml
- path: patch_affinity.yaml
- path: patch_topology_spread_constraint.yaml
- path: patch_logging.yaml
- path: patch_monitoring.yaml
- path: patch_init_containers.yaml


images:
- name: golang-api-server
  newName: qclaogui/golang-api-server
  newTag: IMAGE_TAG