apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaip
spec:
  template:
    spec:
      containers:
      - name: gaip
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-metrics
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-metrics