version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "github.com/blang/semver"

  # # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker
  # - package-ecosystem: "docker"
  #   directory: "/kubernetes/common/grafana-agent"
  #   schedule:
  #     interval: "weekly"
  #     time: "06:00"
  #     timezone: "Asia/Shanghai"
  #   commit-message:
  #     prefix: "[docker] "
  #   reviewers:
  #     - "qclaogui"
  #   open-pull-requests-limit: 2
