name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '💥 Breaking Changes'
    label: 'kind/breaking'
  - title: '🚀 Features'
    labels:
      - 'kind/feature'
  - title: '🎯 Improvements'
    labels:
      - 'kind/improvement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'area/tech-debt'
      - 'area/ci'
  - title: '📝 Documentation'
    labels: 
      - 'area/docs'
      - 'kind/docs'
  - title: '⬆️ Dependencies'
    labels:
      - 'dependencies'
    collapse-after: 5

change-template: '- $TITLE (#$NUMBER)'
sort-by: title
sort-direction: ascending
change-title-escapes: '\<*_&#@`' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-template: '$COMPLETE'
no-changes-template: 'This release contains minor changes and bugfixes.'
template: |
  # Release v$NEXT_MINOR_VERSION

  ## What's Changed
  
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_MINOR_VERSION

  ## New Contributors
  
  $CONTRIBUTORS
  
  🎉 **Thanks to all contributors helping with this release!** 🎉
  
# replacers:
#   - search: '/@(qclaogui|dependabot(?:\[bot\])?)(?:,| |$)/gm'
#     replace: ''

exclude-labels:
  - 'skip-release-notes'
  - 'skip-changelog'

exclude-contributors:
  - 'dependabot[bot]'
  