name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
version-template: '$COMPLETE'
prerelease-identifier: rc
categories:
  - title: '💥 Breaking Changes'
    collapse-after: 15
    label: 'kind/breaking'
  - title: '🚀 Features'
    collapse-after: 15
    labels:
      - 'kind/feature'
  - title: '🎯 Improvements'
    collapse-after: 15
    labels:
      - 'kind/improvement'
  - title: '🐛 Bug Fixes'
    collapse-after: 15
    labels:
      - 'kind/bug'
  - title: '🧰 Maintenance'
    collapse-after: 15
    labels: 
      - 'area/tech-debt'
      - 'area/ci'
      - 'kind/maintenance'
  - title: '📝 Documentation'
    collapse-after: 10
    labels: 
      - 'area/docs'
      - 'kind/docs'
  - title: '⬆️ Dependencies'
    collapse-after: 10
    labels:
      - 'dependencies'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&#@`' # You can add # and @ to disable mentions, and add ` to disable code blocks.
no-changes-template: 'This release contains minor changes and bugfixes.'
template: |
  
  # Release v$NEXT_MINOR_VERSION

  ## What's Changed
  
  $CHANGES
  
  ## New Contributors

  $CONTRIBUTORS

  🎉 **Thanks to all contributors helping with this release!** 🎉

exclude-labels:
  - 'skip-release-notes'
  - 'skip-changelog'
exclude-contributors:
  - 'qclaogui'
  - 'dependabot'
replacers:
  - search: '/\s(?:and )?@dependabot(?:\[bot\])?,?/g'
    replace: ''
