#Copyright © Weifeng Wang <qclaogui@gmail.com>
#Licensed under the Apache License 2.0.

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: qclaogui

helmGlobals:
  chartHome: ../../helm/charts

# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#field-name-helmcharts
helmCharts:
- name: gaip
  # repo: oci://ghcr.io/qclaogui/helm-charts
  # version: 0.0.1
  # kubeVersion: "1.27"
  releaseName: gaip
  namespace: qclaogui
  includeCRDs: false
  skipTests: true
  valuesFile: values-k3d-k3s.yaml

