# https://goreleaser.com/customization/ko/
kos:
- id: gaip-image
  build: gaip
  repository: qclaogui/golang-api-server
  base_image: cgr.dev/chainguard/static
  labels:
    org.opencontainers.image.title: "gaip"
    org.opencontainers.image.source: "https://github.com/qclaogui/golang-api-server"
    org.opencontainers.image.description: "Practices for implementing Google API Improvement Proposals (AIP) in Go."
  env:
    - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - -s -w
    - -extldflags "-static"
    - -X github.com/qclaogui/golang-api-server/pkg/version.Version={{.Version}}
    - -X github.com/qclaogui/golang-api-server/pkg/version.GitCommit={{.ShortCommit}}
    - -X github.com/qclaogui/golang-api-server/pkg/version.BuildDate={{.Date}}
    - -X github.com/qclaogui/golang-api-server/pkg/version.PreReleaseID={{.Env.PRE_RELEASE_ID}}
  platforms:
    - linux/amd64
    - linux/arm64
  tags:
    - latest
    - '{{.Version}}'

  bare: true
  preserve_import_paths: false
  base_import_paths: false
