# https://goreleaser.com/customization/ko/
kos:
- repository: ghcr.io/qclaogui/golang-api-server
  # Base image to publish to use. Default: 'cgr.dev/chainguard/static'
  # base_image: alpine
  env:
    - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - -s -w
    - -extldflags "-static"
    - -X github.com/qclaogui/golang-api-server/pkg/version.Version={{.Version}}
    - -X github.com/qclaogui/golang-api-server/pkg/version.GitCommit={{.ShortCommit}}
    - -X github.com/qclaogui/golang-api-server/pkg/version.BuildDate={{.Date}}
    - -X github.com/qclaogui/golang-api-server/pkg/version.PreReleaseID={{.Env.PRE_RELEASE_ID}}
  platforms:
    - linux/amd64
    - linux/arm64
  tags:
    - latest
    - '{{.Version}}'
  bare: true
  preserve_import_paths: false
  base_import_paths: true
