# https://goreleaser.com/customization/docker/
dockers:
- image_templates:
  - "qclaogui/gaip:{{.Version}}-amd64"
  dockerfile: Dockerfile.goreleaser
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.title=gaip"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.description=Practices for implementing Google API Improvement Proposals (AIP) in Go."
  - "--platform=linux/amd64"
  goos: linux
  goarch: amd64
  skip_push: true
- image_templates:
  - "qclaogui/gaip:{{.Version}}-arm64"
  dockerfile: Dockerfile.goreleaser
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.title=gaip"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.description=Practices for implementing Google API Improvement Proposals (AIP) in Go."
  - "--platform=linux/arm64"
  goos: linux
  goarch: arm64
  skip_push: true


docker_manifests:
- name_template: "qclaogui/gaip:{{.Version}}"
  image_templates:
  - "qclaogui/gaip:{{.Version}}-amd64"
  - "qclaogui/gaip:{{.Version}}-arm64"
  skip_push: true
- name_template: "qclaogui/gaip:latest"
  image_templates:
  - "qclaogui/gaip:{{.Version}}-amd64"
  - "qclaogui/gaip:{{.Version}}-arm64"
  skip_push: true
