release:
  name_template: "{{ .ProjectName }} {{ .Env.RELEASE_DESCRIPTION }}"
  prerelease: auto # this should detect a release candidate and mark it as pre-release in GitHub
  skip_upload: true

builds:
- id: gaip
  main: ./cmd
  binary: bin/gaip
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X github.com/qclaogui/gaip/pkg/version.Version={{.Version}}
  - -X github.com/qclaogui/gaip/pkg/version.GitCommit={{.ShortCommit}}
  - -X github.com/qclaogui/gaip/pkg/version.BuildDate={{.Date}}
  - -X github.com/qclaogui/gaip/pkg/version.PreReleaseID={{.Env.PRE_RELEASE_ID}}

  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  #
  # Default: [ 'darwin', 'linux', 'windows' ]
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

archives:
- builds:
  - gaip
  name_template: "gaip_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  files:
  - none*

checksum:
  name_template: "checksums.txt"

report_sizes: true
