# https://goreleaser.com/customization/docker/
dockers:
  - image_templates:
      - "qclaogui/golang-api-server:{{ .Version }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    dockerfile: "Dockefile.goreleaser"
    use: buildx
    goarch: amd64
    skip_push: true
  - image_templates:
      - "qclaogui/golang-api-server:{{ .Version }}-arm64v8"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
    dockerfile: "Dockefile.goreleaser"
    use: buildx
    goarch: arm64
    skip_push: true

docker_manifests:
  - name_template: "qclaogui/golang-api-server:{{ .Version }}"
    image_templates:
      - "qclaogui/golang-api-server:{{ .Version }}-amd64"
      - "qclaogui/golang-api-server:{{ .Version }}-arm64v8"
    create_flags:
      - --insecure
    push_flags:
      - --insecure
    # skip_push: true
