# use the latest ubuntu environment (18.04) available on travis
dist: xenial

language: go

# Force-enable Go modules.
env:
  - GO111MODULE=on

# Run all the tests with the race detector enabled
matrix:
  include:
    - go: 1.12.x
      script: go test -v -mod=vendor -race ./...
    - go: 1.13.x
      script: go test -v -mod=vendor -race ./...
    - go: 1.14.x
      script: go test -v -mod=vendor -race ./...
# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false