apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: gaip
build:
  artifacts:
    - image: gaip
      ko:
        fromImage: cgr.dev/chainguard/static
        main: ./cmd/gaip

# Profiles
profiles:
  - name: k3d-k3s
    manifests:
      kustomize:
        paths:
          - deploy/base
    # override the default base image with one that supports CGO when running 'skaffold dev'
    activation:
      - command: dev
        kubeContext: k3d-k3s-gaip
    patches:
      - op: replace
        path: /build/artifacts/0/ko/fromImage
        value: cgr.dev/chainguard/glibc-dynamic
      - op: add
        path: /build/artifacts/0/ko/env/0
        value: CGO_ENABLED=1
  
  - name: prod
    build:
      artifacts:
        - image: uhub.service.ucloud.cn/qclaogui/gaip
          kaniko:
            image: uhub.service.ucloud.cn/qclaogui/executor:debug
      cluster: {}
    manifests:
      kustomize:
        paths:
          - deploy/overlays/prod
