apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: gaip
build:
  artifacts:
    - image: gaip
      ko:
        fromImage: cgr.dev/chainguard/static
        main: ./cmd/gaip
profiles:
  - name: k3d-k3s
    activation:
      - kubeContext: k3d-k3s-gaip
        command: dev
    patches:
      - op: replace
        path: /build/artifacts/0/ko/fromImage
        value: cgr.dev/chainguard/glibc-dynamic
      - op: add
        path: /build/artifacts/0/ko/env/0
        value: CGO_ENABLED=1
    manifests:
      kustomize:
        paths:
          - deploy/base
  - name: prod
    build:
      artifacts:
        - image: uhub.service.ucloud.cn/qclaogui/gaip
          kaniko:
            image: uhub.service.ucloud.cn/qclaogui/executor:debug
      cluster: {}
    manifests:
      kustomize:
        paths:
          - deploy/overlays/prod
