apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: gaip
build:
  artifacts:
    - image: gaip
      ko:
        main: ./cmd
  platforms:
    - linux/amd64
manifests:
  rawYaml:
    - deploy/overlays/dev/k8s-all-in-one.yaml
deploy:
  kubectl:
    remoteManifests:
      - deploy/overlays/dev/k8s-all-in-one.yaml
# portForward:
#   - resourceType: Deployment
#     resourceName: gaip
#     namespace: default
#     port: 8080
#     localPort: 8080

profiles:
  - name: dev
    build:
      artifacts:
        - image: qclaogui/gaip
          ko:
            ldflags:
              - -s -w
              - -extldflags "-static"
            main: ./cmd
    manifests:
      rawYaml:
        - deploy/overlays/dev/k8s-all-in-one.yaml
    deploy:
      kubectl:
        remoteManifests:
          - deploy/overlays/dev/k8s-all-in-one.yaml
  - name: prod
    build:
      artifacts:
        - image: uhub.service.ucloud.cn/qclaogui/gaip
          kaniko:
            image: uhub.service.ucloud.cn/qclaogui/executor:debug
      cluster: {}
    manifests:
      kustomize:
        paths:
          - deploy/overlays/prod
