apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api-server
spec:
  template:
    spec:
      containers:
      - name: golang-api-server
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-metrics
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-metrics