apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaip
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
      - name: ucloud-registry
      containers:
      - name: gaip
        # imagePullPolicy: Always
        image: gaip
        ports:
        - name: http-metrics
          containerPort: 8080