# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: gaip

patches:
- path: patch_env.yaml


configMapGenerator:
- literals:
  - APP_PORT=8080
  name: gaip

resources:
- deployment.yaml
- service.yaml
