// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: qclaogui/generativelanguage/v1beta1/retriever_service.proto

package generativelanguagepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a `Corpus`.
type CreateCorpusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `Corpus` to create.
	Corpus        *Corpus `protobuf:"bytes,1,opt,name=corpus,proto3" json:"corpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCorpusRequest) Reset() {
	*x = CreateCorpusRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCorpusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCorpusRequest) ProtoMessage() {}

func (x *CreateCorpusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCorpusRequest.ProtoReflect.Descriptor instead.
func (*CreateCorpusRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCorpusRequest) GetCorpus() *Corpus {
	if x != nil {
		return x.Corpus
	}
	return nil
}

// Request for getting information about a specific `Corpus`.
type GetCorpusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Corpus`.
	// Example: `corpora/my-corpus-123`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCorpusRequest) Reset() {
	*x = GetCorpusRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCorpusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorpusRequest) ProtoMessage() {}

func (x *GetCorpusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorpusRequest.ProtoReflect.Descriptor instead.
func (*GetCorpusRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCorpusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to update a `Corpus`.
type UpdateCorpusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `Corpus` to update.
	Corpus *Corpus `protobuf:"bytes,1,opt,name=corpus,proto3" json:"corpus,omitempty"`
	// Required. The list of fields to update.
	// Currently, this only supports updating `display_name`.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCorpusRequest) Reset() {
	*x = UpdateCorpusRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCorpusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCorpusRequest) ProtoMessage() {}

func (x *UpdateCorpusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCorpusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCorpusRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCorpusRequest) GetCorpus() *Corpus {
	if x != nil {
		return x.Corpus
	}
	return nil
}

func (x *UpdateCorpusRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request to delete a `Corpus`.
type DeleteCorpusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the `Corpus`.
	// Example: `corpora/my-corpus-123`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. If set to true, any `Document`s and objects related to this
	// `Corpus` will also be deleted.
	//
	// If false (the default), a `FAILED_PRECONDITION` error will be returned if
	// `Corpus` contains any `Document`s.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCorpusRequest) Reset() {
	*x = DeleteCorpusRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCorpusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCorpusRequest) ProtoMessage() {}

func (x *DeleteCorpusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCorpusRequest.ProtoReflect.Descriptor instead.
func (*DeleteCorpusRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCorpusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteCorpusRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Request for listing `Corpora`.
type ListCorporaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The maximum number of `Corpora` to return (per page).
	// The service may return fewer `Corpora`.
	//
	// If unspecified, at most 10 `Corpora` will be returned.
	// The maximum size limit is 20 `Corpora` per page.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token, received from a previous `ListCorpora` call.
	//
	// Provide the `next_page_token` returned in the response as an argument to
	// the next request to retrieve the next page.
	//
	// When paginating, all other parameters provided to `ListCorpora`
	// must match the call that provided the page token.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCorporaRequest) Reset() {
	*x = ListCorporaRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCorporaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCorporaRequest) ProtoMessage() {}

func (x *ListCorporaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCorporaRequest.ProtoReflect.Descriptor instead.
func (*ListCorporaRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListCorporaRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCorporaRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response from `ListCorpora` containing a paginated list of `Corpora`.
// The results are sorted by ascending `corpus.create_time`.
type ListCorporaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The returned corpora.
	Corpora []*Corpus `protobuf:"bytes,1,rep,name=corpora,proto3" json:"corpora,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no more pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCorporaResponse) Reset() {
	*x = ListCorporaResponse{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCorporaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCorporaResponse) ProtoMessage() {}

func (x *ListCorporaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCorporaResponse.ProtoReflect.Descriptor instead.
func (*ListCorporaResponse) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListCorporaResponse) GetCorpora() []*Corpus {
	if x != nil {
		return x.Corpora
	}
	return nil
}

func (x *ListCorporaResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request for querying a `Corpus`.
type QueryCorpusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Corpus` to query.
	// Example: `corpora/my-corpus-123`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. Query string to perform semantic search.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Optional. Filter for `Chunk` and `Document` metadata. Each `MetadataFilter`
	// object should correspond to a unique key. Multiple `MetadataFilter` objects
	// are joined by logical "AND"s.
	//
	// Example query at document level:
	// (year >= 2020 OR year < 2010) AND (genre = drama OR genre = action)
	//
	// `MetadataFilter` object list:
	//
	//	metadata_filters = [
	//	{key = "document.custom_metadata.year"
	//	 conditions = [{int_value = 2020, operation = GREATER_EQUAL},
	//	               {int_value = 2010, operation = LESS}]},
	//	{key = "document.custom_metadata.year"
	//	 conditions = [{int_value = 2020, operation = GREATER_EQUAL},
	//	               {int_value = 2010, operation = LESS}]},
	//	{key = "document.custom_metadata.genre"
	//	 conditions = [{string_value = "drama", operation = EQUAL},
	//	               {string_value = "action", operation = EQUAL}]}]
	//
	// Example query at chunk level for a numeric range of values:
	// (year > 2015 AND year <= 2020)
	//
	// `MetadataFilter` object list:
	//
	//	metadata_filters = [
	//	{key = "chunk.custom_metadata.year"
	//	 conditions = [{int_value = 2015, operation = GREATER}]},
	//	{key = "chunk.custom_metadata.year"
	//	 conditions = [{int_value = 2020, operation = LESS_EQUAL}]}]
	//
	// Note: "AND"s for the same key are only supported for numeric values. String
	// values only support "OR"s for the same key.
	MetadataFilters []*MetadataFilter `protobuf:"bytes,3,rep,name=metadata_filters,json=metadataFilters,proto3" json:"metadata_filters,omitempty"`
	// Optional. The maximum number of `Chunk`s to return.
	// The service may return fewer `Chunk`s.
	//
	// If unspecified, at most 10 `Chunk`s will be returned.
	// The maximum specified result count is 100.
	ResultsCount  int32 `protobuf:"varint,4,opt,name=results_count,json=resultsCount,proto3" json:"results_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCorpusRequest) Reset() {
	*x = QueryCorpusRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCorpusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCorpusRequest) ProtoMessage() {}

func (x *QueryCorpusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCorpusRequest.ProtoReflect.Descriptor instead.
func (*QueryCorpusRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{6}
}

func (x *QueryCorpusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryCorpusRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryCorpusRequest) GetMetadataFilters() []*MetadataFilter {
	if x != nil {
		return x.MetadataFilters
	}
	return nil
}

func (x *QueryCorpusRequest) GetResultsCount() int32 {
	if x != nil {
		return x.ResultsCount
	}
	return 0
}

// Response from `QueryCorpus` containing a list of relevant chunks.
type QueryCorpusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The relevant chunks.
	RelevantChunks []*RelevantChunk `protobuf:"bytes,1,rep,name=relevant_chunks,json=relevantChunks,proto3" json:"relevant_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryCorpusResponse) Reset() {
	*x = QueryCorpusResponse{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCorpusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCorpusResponse) ProtoMessage() {}

func (x *QueryCorpusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCorpusResponse.ProtoReflect.Descriptor instead.
func (*QueryCorpusResponse) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{7}
}

func (x *QueryCorpusResponse) GetRelevantChunks() []*RelevantChunk {
	if x != nil {
		return x.RelevantChunks
	}
	return nil
}

// The information for a chunk relevant to a query.
type RelevantChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `Chunk` relevance to the query.
	ChunkRelevanceScore float32 `protobuf:"fixed32,1,opt,name=chunk_relevance_score,json=chunkRelevanceScore,proto3" json:"chunk_relevance_score,omitempty"`
	// `Chunk` associated with the query.
	Chunk         *Chunk `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelevantChunk) Reset() {
	*x = RelevantChunk{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelevantChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelevantChunk) ProtoMessage() {}

func (x *RelevantChunk) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelevantChunk.ProtoReflect.Descriptor instead.
func (*RelevantChunk) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{8}
}

func (x *RelevantChunk) GetChunkRelevanceScore() float32 {
	if x != nil {
		return x.ChunkRelevanceScore
	}
	return 0
}

func (x *RelevantChunk) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Request to create a `Document`.
type CreateDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Corpus` where this `Document` will be created.
	// Example: `corpora/my-corpus-123`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The `Document` to create.
	Document      *Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateDocumentRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateDocumentRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

// Request for getting information about a specific `Document`.
type GetDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Document` to retrieve.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to update a `Document`.
type UpdateDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `Document` to update.
	Document *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// Required. The list of fields to update.
	// Currently, this only supports updating `display_name` and
	// `custom_metadata`.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDocumentRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *UpdateDocumentRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request to delete a `Document`.
type DeleteDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the `Document` to delete.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. If set to true, any `Chunk`s and objects related to this
	// `Document` will also be deleted.
	//
	// If false (the default), a `FAILED_PRECONDITION` error will be returned if
	// `Document` contains any `Chunk`s.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteDocumentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Request for listing `Document`s.
type ListDocumentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Corpus` containing `Document`s.
	// Example: `corpora/my-corpus-123`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of `Document`s to return (per page).
	// The service may return fewer `Document`s.
	//
	// If unspecified, at most 10 `Document`s will be returned.
	// The maximum size limit is 20 `Document`s per page.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token, received from a previous `ListDocuments` call.
	//
	// Provide the `next_page_token` returned in the response as an argument to
	// the next request to retrieve the next page.
	//
	// When paginating, all other parameters provided to `ListDocuments`
	// must match the call that provided the page token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListDocumentsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response from `ListDocuments` containing a paginated list of `Document`s.
// The `Document`s are sorted by ascending `document.create_time`.
type ListDocumentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The returned `Document`s.
	Documents []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no more pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request for querying a `Document`.
type QueryDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Document` to query.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. Query string to perform semantic search.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// Optional. The maximum number of `Chunk`s to return.
	// The service may return fewer `Chunk`s.
	//
	// If unspecified, at most 10 `Chunk`s will be returned.
	// The maximum specified result count is 100.
	ResultsCount int32 `protobuf:"varint,3,opt,name=results_count,json=resultsCount,proto3" json:"results_count,omitempty"`
	// Optional. Filter for `Chunk` metadata. Each `MetadataFilter` object should
	// correspond to a unique key. Multiple `MetadataFilter` objects are joined by
	// logical "AND"s.
	//
	// Note: `Document`-level filtering is not supported for this request because
	// a `Document` name is already specified.
	//
	// Example query:
	// (year >= 2020 OR year < 2010) AND (genre = drama OR genre = action)
	//
	// `MetadataFilter` object list:
	//
	//	metadata_filters = [
	//	{key = "chunk.custom_metadata.year"
	//	 conditions = [{int_value = 2020, operation = GREATER_EQUAL},
	//	               {int_value = 2010, operation = LESS}},
	//	{key = "chunk.custom_metadata.genre"
	//	 conditions = [{string_value = "drama", operation = EQUAL},
	//	               {string_value = "action", operation = EQUAL}}]
	//
	// Example query for a numeric range of values:
	// (year > 2015 AND year <= 2020)
	//
	// `MetadataFilter` object list:
	//
	//	metadata_filters = [
	//	{key = "chunk.custom_metadata.year"
	//	 conditions = [{int_value = 2015, operation = GREATER}]},
	//	{key = "chunk.custom_metadata.year"
	//	 conditions = [{int_value = 2020, operation = LESS_EQUAL}]}]
	//
	// Note: "AND"s for the same key are only supported for numeric values. String
	// values only support "OR"s for the same key.
	MetadataFilters []*MetadataFilter `protobuf:"bytes,4,rep,name=metadata_filters,json=metadataFilters,proto3" json:"metadata_filters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryDocumentRequest) Reset() {
	*x = QueryDocumentRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDocumentRequest) ProtoMessage() {}

func (x *QueryDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDocumentRequest.ProtoReflect.Descriptor instead.
func (*QueryDocumentRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{15}
}

func (x *QueryDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryDocumentRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryDocumentRequest) GetResultsCount() int32 {
	if x != nil {
		return x.ResultsCount
	}
	return 0
}

func (x *QueryDocumentRequest) GetMetadataFilters() []*MetadataFilter {
	if x != nil {
		return x.MetadataFilters
	}
	return nil
}

// Response from `QueryDocument` containing a list of relevant chunks.
type QueryDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The returned relevant chunks.
	RelevantChunks []*RelevantChunk `protobuf:"bytes,1,rep,name=relevant_chunks,json=relevantChunks,proto3" json:"relevant_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryDocumentResponse) Reset() {
	*x = QueryDocumentResponse{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDocumentResponse) ProtoMessage() {}

func (x *QueryDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDocumentResponse.ProtoReflect.Descriptor instead.
func (*QueryDocumentResponse) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{16}
}

func (x *QueryDocumentResponse) GetRelevantChunks() []*RelevantChunk {
	if x != nil {
		return x.RelevantChunks
	}
	return nil
}

// Request to create a `Chunk`.
type CreateChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Document` where this `Chunk` will be created.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The `Chunk` to create.
	Chunk         *Chunk `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChunkRequest) Reset() {
	*x = CreateChunkRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChunkRequest) ProtoMessage() {}

func (x *CreateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChunkRequest.ProtoReflect.Descriptor instead.
func (*CreateChunkRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateChunkRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateChunkRequest) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Request to batch create `Chunk`s.
type BatchCreateChunksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The name of the `Document` where this batch of `Chunk`s will be
	// created. The parent field in every `CreateChunkRequest` must match this
	// value. Example: `corpora/my-corpus-123/documents/the-doc-abc`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The request messages specifying the `Chunk`s to create.
	// A maximum of 100 `Chunk`s can be created in a batch.
	Requests      []*CreateChunkRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateChunksRequest) Reset() {
	*x = BatchCreateChunksRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateChunksRequest) ProtoMessage() {}

func (x *BatchCreateChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateChunksRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateChunksRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{18}
}

func (x *BatchCreateChunksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchCreateChunksRequest) GetRequests() []*CreateChunkRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// Response from `BatchCreateChunks` containing a list of created `Chunk`s.
type BatchCreateChunksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `Chunk`s created.
	Chunks        []*Chunk `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateChunksResponse) Reset() {
	*x = BatchCreateChunksResponse{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateChunksResponse) ProtoMessage() {}

func (x *BatchCreateChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateChunksResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateChunksResponse) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{19}
}

func (x *BatchCreateChunksResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// Request for getting information about a specific `Chunk`.
type GetChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Chunk` to retrieve.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc/chunks/some-chunk`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetChunkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to update a `Chunk`.
type UpdateChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `Chunk` to update.
	Chunk *Chunk `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// Required. The list of fields to update.
	// Currently, this only supports updating `custom_metadata` and `data`.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChunkRequest) Reset() {
	*x = UpdateChunkRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChunkRequest) ProtoMessage() {}

func (x *UpdateChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChunkRequest.ProtoReflect.Descriptor instead.
func (*UpdateChunkRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateChunkRequest) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *UpdateChunkRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request to batch update `Chunk`s.
type BatchUpdateChunksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The name of the `Document` containing the `Chunk`s to update.
	// The parent field in every `UpdateChunkRequest` must match this value.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The request messages specifying the `Chunk`s to update.
	// A maximum of 100 `Chunk`s can be updated in a batch.
	Requests      []*UpdateChunkRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateChunksRequest) Reset() {
	*x = BatchUpdateChunksRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateChunksRequest) ProtoMessage() {}

func (x *BatchUpdateChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateChunksRequest.ProtoReflect.Descriptor instead.
func (*BatchUpdateChunksRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{22}
}

func (x *BatchUpdateChunksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchUpdateChunksRequest) GetRequests() []*UpdateChunkRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// Response from `BatchUpdateChunks` containing a list of updated `Chunk`s.
type BatchUpdateChunksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `Chunk`s updated.
	Chunks        []*Chunk `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpdateChunksResponse) Reset() {
	*x = BatchUpdateChunksResponse{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpdateChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpdateChunksResponse) ProtoMessage() {}

func (x *BatchUpdateChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpdateChunksResponse.ProtoReflect.Descriptor instead.
func (*BatchUpdateChunksResponse) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{23}
}

func (x *BatchUpdateChunksResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// Request to delete a `Chunk`.
type DeleteChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the `Chunk` to delete.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc/chunks/some-chunk`
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteChunkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to batch delete `Chunk`s.
type BatchDeleteChunksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The name of the `Document` containing the `Chunk`s to delete.
	// The parent field in every `DeleteChunkRequest` must match this value.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The request messages specifying the `Chunk`s to delete.
	Requests      []*DeleteChunkRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteChunksRequest) Reset() {
	*x = BatchDeleteChunksRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteChunksRequest) ProtoMessage() {}

func (x *BatchDeleteChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteChunksRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteChunksRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{25}
}

func (x *BatchDeleteChunksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchDeleteChunksRequest) GetRequests() []*DeleteChunkRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// Request for listing `Chunk`s.
type ListChunksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the `Document` containing `Chunk`s.
	// Example: `corpora/my-corpus-123/documents/the-doc-abc`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Optional. The maximum number of `Chunk`s to return (per page).
	// The service may return fewer `Chunk`s.
	//
	// If unspecified, at most 10 `Chunk`s will be returned.
	// The maximum size limit is 100 `Chunk`s per page.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A page token, received from a previous `ListChunks` call.
	//
	// Provide the `next_page_token` returned in the response as an argument to
	// the next request to retrieve the next page.
	//
	// When paginating, all other parameters provided to `ListChunks`
	// must match the call that provided the page token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChunksRequest) Reset() {
	*x = ListChunksRequest{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChunksRequest) ProtoMessage() {}

func (x *ListChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChunksRequest.ProtoReflect.Descriptor instead.
func (*ListChunksRequest) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{26}
}

func (x *ListChunksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListChunksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChunksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response from `ListChunks` containing a paginated list of `Chunk`s.
// The `Chunk`s are sorted by ascending `chunk.create_time`.
type ListChunksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The returned `Chunk`s.
	Chunks []*Chunk `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no more pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChunksResponse) Reset() {
	*x = ListChunksResponse{}
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChunksResponse) ProtoMessage() {}

func (x *ListChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChunksResponse.ProtoReflect.Descriptor instead.
func (*ListChunksResponse) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP(), []int{27}
}

func (x *ListChunksResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ListChunksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_qclaogui_generativelanguage_v1beta1_retriever_service_proto protoreflect.FileDescriptor

const file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDesc = "" +
	"\n" +
	";qclaogui/generativelanguage/v1beta1/retriever_service.proto\x12#qclaogui.generativelanguage.v1beta1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a3qclaogui/generativelanguage/v1beta1/retriever.proto\"`\n" +
	"\x13CreateCorpusRequest\x12I\n" +
	"\x06corpus\x18\x01 \x01(\v2+.qclaogui.generativelanguage.v1beta1.CorpusB\x04\xe2A\x01\x02R\x06corpus\"W\n" +
	"\x10GetCorpusRequest\x12C\n" +
	"\x04name\x18\x01 \x01(\tB/\xe2A\x01\x02\xfaA(\n" +
	"&generativelanguage.qclaogui.com/CorpusR\x04name\"\xa3\x01\n" +
	"\x13UpdateCorpusRequest\x12I\n" +
	"\x06corpus\x18\x01 \x01(\v2+.qclaogui.generativelanguage.v1beta1.CorpusB\x04\xe2A\x01\x02R\x06corpus\x12A\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x04\xe2A\x01\x02R\n" +
	"updateMask\"v\n" +
	"\x13DeleteCorpusRequest\x12C\n" +
	"\x04name\x18\x01 \x01(\tB/\xe2A\x01\x02\xfaA(\n" +
	"&generativelanguage.qclaogui.com/CorpusR\x04name\x12\x1a\n" +
	"\x05force\x18\x02 \x01(\bB\x04\xe2A\x01\x01R\x05force\"\\\n" +
	"\x12ListCorporaRequest\x12!\n" +
	"\tpage_size\x18\x01 \x01(\x05B\x04\xe2A\x01\x01R\bpageSize\x12#\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tB\x04\xe2A\x01\x01R\tpageToken\"\x84\x01\n" +
	"\x13ListCorporaResponse\x12E\n" +
	"\acorpora\x18\x01 \x03(\v2+.qclaogui.generativelanguage.v1beta1.CorpusR\acorpora\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x86\x02\n" +
	"\x12QueryCorpusRequest\x12C\n" +
	"\x04name\x18\x01 \x01(\tB/\xe2A\x01\x02\xfaA(\n" +
	"&generativelanguage.qclaogui.com/CorpusR\x04name\x12\x1a\n" +
	"\x05query\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05query\x12d\n" +
	"\x10metadata_filters\x18\x03 \x03(\v23.qclaogui.generativelanguage.v1beta1.MetadataFilterB\x04\xe2A\x01\x01R\x0fmetadataFilters\x12)\n" +
	"\rresults_count\x18\x04 \x01(\x05B\x04\xe2A\x01\x01R\fresultsCount\"r\n" +
	"\x13QueryCorpusResponse\x12[\n" +
	"\x0frelevant_chunks\x18\x01 \x03(\v22.qclaogui.generativelanguage.v1beta1.RelevantChunkR\x0erelevantChunks\"\x85\x01\n" +
	"\rRelevantChunk\x122\n" +
	"\x15chunk_relevance_score\x18\x01 \x01(\x02R\x13chunkRelevanceScore\x12@\n" +
	"\x05chunk\x18\x02 \x01(\v2*.qclaogui.generativelanguage.v1beta1.ChunkR\x05chunk\"\xb3\x01\n" +
	"\x15CreateDocumentRequest\x12I\n" +
	"\x06parent\x18\x01 \x01(\tB1\xe2A\x01\x02\xfaA*\x12(generativelanguage.qclaogui.com/DocumentR\x06parent\x12O\n" +
	"\bdocument\x18\x02 \x01(\v2-.qclaogui.generativelanguage.v1beta1.DocumentB\x04\xe2A\x01\x02R\bdocument\"[\n" +
	"\x12GetDocumentRequest\x12E\n" +
	"\x04name\x18\x01 \x01(\tB1\xe2A\x01\x02\xfaA*\n" +
	"(generativelanguage.qclaogui.com/DocumentR\x04name\"\xab\x01\n" +
	"\x15UpdateDocumentRequest\x12O\n" +
	"\bdocument\x18\x01 \x01(\v2-.qclaogui.generativelanguage.v1beta1.DocumentB\x04\xe2A\x01\x02R\bdocument\x12A\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x04\xe2A\x01\x02R\n" +
	"updateMask\"z\n" +
	"\x15DeleteDocumentRequest\x12E\n" +
	"\x04name\x18\x01 \x01(\tB1\xe2A\x01\x02\xfaA*\n" +
	"(generativelanguage.qclaogui.com/DocumentR\x04name\x12\x1a\n" +
	"\x05force\x18\x02 \x01(\bB\x04\xe2A\x01\x01R\x05force\"\xa9\x01\n" +
	"\x14ListDocumentsRequest\x12I\n" +
	"\x06parent\x18\x01 \x01(\tB1\xe2A\x01\x02\xfaA*\x12(generativelanguage.qclaogui.com/DocumentR\x06parent\x12!\n" +
	"\tpage_size\x18\x02 \x01(\x05B\x04\xe2A\x01\x01R\bpageSize\x12#\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\tpageToken\"\x8c\x01\n" +
	"\x15ListDocumentsResponse\x12K\n" +
	"\tdocuments\x18\x01 \x03(\v2-.qclaogui.generativelanguage.v1beta1.DocumentR\tdocuments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8a\x02\n" +
	"\x14QueryDocumentRequest\x12E\n" +
	"\x04name\x18\x01 \x01(\tB1\xe2A\x01\x02\xfaA*\n" +
	"(generativelanguage.qclaogui.com/DocumentR\x04name\x12\x1a\n" +
	"\x05query\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x05query\x12)\n" +
	"\rresults_count\x18\x03 \x01(\x05B\x04\xe2A\x01\x01R\fresultsCount\x12d\n" +
	"\x10metadata_filters\x18\x04 \x03(\v23.qclaogui.generativelanguage.v1beta1.MetadataFilterB\x04\xe2A\x01\x01R\x0fmetadataFilters\"t\n" +
	"\x15QueryDocumentResponse\x12[\n" +
	"\x0frelevant_chunks\x18\x01 \x03(\v22.qclaogui.generativelanguage.v1beta1.RelevantChunkR\x0erelevantChunks\"\xa4\x01\n" +
	"\x12CreateChunkRequest\x12F\n" +
	"\x06parent\x18\x01 \x01(\tB.\xe2A\x01\x02\xfaA'\x12%generativelanguage.qclaogui.com/ChunkR\x06parent\x12F\n" +
	"\x05chunk\x18\x02 \x01(\v2*.qclaogui.generativelanguage.v1beta1.ChunkB\x04\xe2A\x01\x02R\x05chunk\"\xbd\x01\n" +
	"\x18BatchCreateChunksRequest\x12F\n" +
	"\x06parent\x18\x01 \x01(\tB.\xe2A\x01\x01\xfaA'\x12%generativelanguage.qclaogui.com/ChunkR\x06parent\x12Y\n" +
	"\brequests\x18\x02 \x03(\v27.qclaogui.generativelanguage.v1beta1.CreateChunkRequestB\x04\xe2A\x01\x02R\brequests\"_\n" +
	"\x19BatchCreateChunksResponse\x12B\n" +
	"\x06chunks\x18\x01 \x03(\v2*.qclaogui.generativelanguage.v1beta1.ChunkR\x06chunks\"U\n" +
	"\x0fGetChunkRequest\x12B\n" +
	"\x04name\x18\x01 \x01(\tB.\xe2A\x01\x02\xfaA'\n" +
	"%generativelanguage.qclaogui.com/ChunkR\x04name\"\x9f\x01\n" +
	"\x12UpdateChunkRequest\x12F\n" +
	"\x05chunk\x18\x01 \x01(\v2*.qclaogui.generativelanguage.v1beta1.ChunkB\x04\xe2A\x01\x02R\x05chunk\x12A\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x04\xe2A\x01\x02R\n" +
	"updateMask\"\xbd\x01\n" +
	"\x18BatchUpdateChunksRequest\x12F\n" +
	"\x06parent\x18\x01 \x01(\tB.\xe2A\x01\x01\xfaA'\x12%generativelanguage.qclaogui.com/ChunkR\x06parent\x12Y\n" +
	"\brequests\x18\x02 \x03(\v27.qclaogui.generativelanguage.v1beta1.UpdateChunkRequestB\x04\xe2A\x01\x02R\brequests\"_\n" +
	"\x19BatchUpdateChunksResponse\x12B\n" +
	"\x06chunks\x18\x01 \x03(\v2*.qclaogui.generativelanguage.v1beta1.ChunkR\x06chunks\"X\n" +
	"\x12DeleteChunkRequest\x12B\n" +
	"\x04name\x18\x01 \x01(\tB.\xe2A\x01\x02\xfaA'\n" +
	"%generativelanguage.qclaogui.com/ChunkR\x04name\"\xbd\x01\n" +
	"\x18BatchDeleteChunksRequest\x12F\n" +
	"\x06parent\x18\x01 \x01(\tB.\xe2A\x01\x01\xfaA'\x12%generativelanguage.qclaogui.com/ChunkR\x06parent\x12Y\n" +
	"\brequests\x18\x02 \x03(\v27.qclaogui.generativelanguage.v1beta1.DeleteChunkRequestB\x04\xe2A\x01\x02R\brequests\"\xa3\x01\n" +
	"\x11ListChunksRequest\x12F\n" +
	"\x06parent\x18\x01 \x01(\tB.\xe2A\x01\x02\xfaA'\x12%generativelanguage.qclaogui.com/ChunkR\x06parent\x12!\n" +
	"\tpage_size\x18\x02 \x01(\x05B\x04\xe2A\x01\x01R\bpageSize\x12#\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\tpageToken\"\x80\x01\n" +
	"\x12ListChunksResponse\x12B\n" +
	"\x06chunks\x18\x01 \x03(\v2*.qclaogui.generativelanguage.v1beta1.ChunkR\x06chunks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xf2\x1c\n" +
	"\x10RetrieverService\x12\x9f\x01\n" +
	"\fCreateCorpus\x128.qclaogui.generativelanguage.v1beta1.CreateCorpusRequest\x1a+.qclaogui.generativelanguage.v1beta1.Corpus\"(\xdaA\x06corpus\x82\xd3\xe4\x93\x02\x19:\x06corpus\"\x0f/v1beta/corpora\x12\x98\x01\n" +
	"\tGetCorpus\x125.qclaogui.generativelanguage.v1beta1.GetCorpusRequest\x1a+.qclaogui.generativelanguage.v1beta1.Corpus\"'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1beta/{name=corpora/*}\x12\xbb\x01\n" +
	"\fUpdateCorpus\x128.qclaogui.generativelanguage.v1beta1.UpdateCorpusRequest\x1a+.qclaogui.generativelanguage.v1beta1.Corpus\"D\xdaA\x12corpus,update_mask\x82\xd3\xe4\x93\x02):\x06corpus2\x1f/v1beta/{corpus.name=corpora/*}\x12\x89\x01\n" +
	"\fDeleteCorpus\x128.qclaogui.generativelanguage.v1beta1.DeleteCorpusRequest\x1a\x16.google.protobuf.Empty\"'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1a*\x18/v1beta/{name=corpora/*}\x12\x99\x01\n" +
	"\vListCorpora\x127.qclaogui.generativelanguage.v1beta1.ListCorporaRequest\x1a8.qclaogui.generativelanguage.v1beta1.ListCorporaResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1beta/corpora\x12\xab\x01\n" +
	"\vQueryCorpus\x127.qclaogui.generativelanguage.v1beta1.QueryCorpusRequest\x1a8.qclaogui.generativelanguage.v1beta1.QueryCorpusResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1beta/{name=corpora/*}:query\x12\xc5\x01\n" +
	"\x0eCreateDocument\x12:.qclaogui.generativelanguage.v1beta1.CreateDocumentRequest\x1a-.qclaogui.generativelanguage.v1beta1.Document\"H\xdaA\x0fparent,document\x82\xd3\xe4\x93\x020:\bdocument\"$/v1beta/{parent=corpora/*}/documents\x12\xaa\x01\n" +
	"\vGetDocument\x127.qclaogui.generativelanguage.v1beta1.GetDocumentRequest\x1a-.qclaogui.generativelanguage.v1beta1.Document\"3\xdaA\x04name\x82\xd3\xe4\x93\x02&\x12$/v1beta/{name=corpora/*/documents/*}\x12\xd3\x01\n" +
	"\x0eUpdateDocument\x12:.qclaogui.generativelanguage.v1beta1.UpdateDocumentRequest\x1a-.qclaogui.generativelanguage.v1beta1.Document\"V\xdaA\x14document,update_mask\x82\xd3\xe4\x93\x029:\bdocument2-/v1beta/{document.name=corpora/*/documents/*}\x12\x99\x01\n" +
	"\x0eDeleteDocument\x12:.qclaogui.generativelanguage.v1beta1.DeleteDocumentRequest\x1a\x16.google.protobuf.Empty\"3\xdaA\x04name\x82\xd3\xe4\x93\x02&*$/v1beta/{name=corpora/*/documents/*}\x12\xbd\x01\n" +
	"\rListDocuments\x129.qclaogui.generativelanguage.v1beta1.ListDocumentsRequest\x1a:.qclaogui.generativelanguage.v1beta1.ListDocumentsResponse\"5\xdaA\x06parent\x82\xd3\xe4\x93\x02&\x12$/v1beta/{parent=corpora/*}/documents\x12\xbd\x01\n" +
	"\rQueryDocument\x129.qclaogui.generativelanguage.v1beta1.QueryDocumentRequest\x1a:.qclaogui.generativelanguage.v1beta1.QueryDocumentResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1beta/{name=corpora/*/documents/*}:query\x12\xbf\x01\n" +
	"\vCreateChunk\x127.qclaogui.generativelanguage.v1beta1.CreateChunkRequest\x1a*.qclaogui.generativelanguage.v1beta1.Chunk\"K\xdaA\fparent,chunk\x82\xd3\xe4\x93\x026:\x05chunk\"-/v1beta/{parent=corpora/*/documents/*}/chunks\x12\xd8\x01\n" +
	"\x11BatchCreateChunks\x12=.qclaogui.generativelanguage.v1beta1.BatchCreateChunksRequest\x1a>.qclaogui.generativelanguage.v1beta1.BatchCreateChunksResponse\"D\x82\xd3\xe4\x93\x02>:\x01*\"9/v1beta/{parent=corpora/*/documents/*}/chunks:batchCreate\x12\xaa\x01\n" +
	"\bGetChunk\x124.qclaogui.generativelanguage.v1beta1.GetChunkRequest\x1a*.qclaogui.generativelanguage.v1beta1.Chunk\"<\xdaA\x04name\x82\xd3\xe4\x93\x02/\x12-/v1beta/{name=corpora/*/documents/*/chunks/*}\x12\xca\x01\n" +
	"\vUpdateChunk\x127.qclaogui.generativelanguage.v1beta1.UpdateChunkRequest\x1a*.qclaogui.generativelanguage.v1beta1.Chunk\"V\xdaA\x11chunk,update_mask\x82\xd3\xe4\x93\x02<:\x05chunk23/v1beta/{chunk.name=corpora/*/documents/*/chunks/*}\x12\xd8\x01\n" +
	"\x11BatchUpdateChunks\x12=.qclaogui.generativelanguage.v1beta1.BatchUpdateChunksRequest\x1a>.qclaogui.generativelanguage.v1beta1.BatchUpdateChunksResponse\"D\x82\xd3\xe4\x93\x02>:\x01*\"9/v1beta/{parent=corpora/*/documents/*}/chunks:batchUpdate\x12\x9c\x01\n" +
	"\vDeleteChunk\x127.qclaogui.generativelanguage.v1beta1.DeleteChunkRequest\x1a\x16.google.protobuf.Empty\"<\xdaA\x04name\x82\xd3\xe4\x93\x02/*-/v1beta/{name=corpora/*/documents/*/chunks/*}\x12\xb0\x01\n" +
	"\x11BatchDeleteChunks\x12=.qclaogui.generativelanguage.v1beta1.BatchDeleteChunksRequest\x1a\x16.google.protobuf.Empty\"D\x82\xd3\xe4\x93\x02>:\x01*\"9/v1beta/{parent=corpora/*/documents/*}/chunks:batchDelete\x12\xbd\x01\n" +
	"\n" +
	"ListChunks\x126.qclaogui.generativelanguage.v1beta1.ListChunksRequest\x1a7.qclaogui.generativelanguage.v1beta1.ListChunksResponse\">\xdaA\x06parent\x82\xd3\xe4\x93\x02/\x12-/v1beta/{parent=corpora/*/documents/*}/chunks\x1a\"\xcaA\x1fgenerativelanguage.qclaogui.comBVZTgithub.com/qclaogui/gaip/genproto/generativelanguage/apiv1beta1/generativelanguagepbb\x06proto3"

var (
	file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescOnce sync.Once
	file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescData []byte
)

func file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescGZIP() []byte {
	file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescOnce.Do(func() {
		file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDesc), len(file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDesc)))
	})
	return file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDescData
}

var (
	file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
	file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_goTypes  = []any{
		(*CreateCorpusRequest)(nil),       // 0: qclaogui.generativelanguage.v1beta1.CreateCorpusRequest
		(*GetCorpusRequest)(nil),          // 1: qclaogui.generativelanguage.v1beta1.GetCorpusRequest
		(*UpdateCorpusRequest)(nil),       // 2: qclaogui.generativelanguage.v1beta1.UpdateCorpusRequest
		(*DeleteCorpusRequest)(nil),       // 3: qclaogui.generativelanguage.v1beta1.DeleteCorpusRequest
		(*ListCorporaRequest)(nil),        // 4: qclaogui.generativelanguage.v1beta1.ListCorporaRequest
		(*ListCorporaResponse)(nil),       // 5: qclaogui.generativelanguage.v1beta1.ListCorporaResponse
		(*QueryCorpusRequest)(nil),        // 6: qclaogui.generativelanguage.v1beta1.QueryCorpusRequest
		(*QueryCorpusResponse)(nil),       // 7: qclaogui.generativelanguage.v1beta1.QueryCorpusResponse
		(*RelevantChunk)(nil),             // 8: qclaogui.generativelanguage.v1beta1.RelevantChunk
		(*CreateDocumentRequest)(nil),     // 9: qclaogui.generativelanguage.v1beta1.CreateDocumentRequest
		(*GetDocumentRequest)(nil),        // 10: qclaogui.generativelanguage.v1beta1.GetDocumentRequest
		(*UpdateDocumentRequest)(nil),     // 11: qclaogui.generativelanguage.v1beta1.UpdateDocumentRequest
		(*DeleteDocumentRequest)(nil),     // 12: qclaogui.generativelanguage.v1beta1.DeleteDocumentRequest
		(*ListDocumentsRequest)(nil),      // 13: qclaogui.generativelanguage.v1beta1.ListDocumentsRequest
		(*ListDocumentsResponse)(nil),     // 14: qclaogui.generativelanguage.v1beta1.ListDocumentsResponse
		(*QueryDocumentRequest)(nil),      // 15: qclaogui.generativelanguage.v1beta1.QueryDocumentRequest
		(*QueryDocumentResponse)(nil),     // 16: qclaogui.generativelanguage.v1beta1.QueryDocumentResponse
		(*CreateChunkRequest)(nil),        // 17: qclaogui.generativelanguage.v1beta1.CreateChunkRequest
		(*BatchCreateChunksRequest)(nil),  // 18: qclaogui.generativelanguage.v1beta1.BatchCreateChunksRequest
		(*BatchCreateChunksResponse)(nil), // 19: qclaogui.generativelanguage.v1beta1.BatchCreateChunksResponse
		(*GetChunkRequest)(nil),           // 20: qclaogui.generativelanguage.v1beta1.GetChunkRequest
		(*UpdateChunkRequest)(nil),        // 21: qclaogui.generativelanguage.v1beta1.UpdateChunkRequest
		(*BatchUpdateChunksRequest)(nil),  // 22: qclaogui.generativelanguage.v1beta1.BatchUpdateChunksRequest
		(*BatchUpdateChunksResponse)(nil), // 23: qclaogui.generativelanguage.v1beta1.BatchUpdateChunksResponse
		(*DeleteChunkRequest)(nil),        // 24: qclaogui.generativelanguage.v1beta1.DeleteChunkRequest
		(*BatchDeleteChunksRequest)(nil),  // 25: qclaogui.generativelanguage.v1beta1.BatchDeleteChunksRequest
		(*ListChunksRequest)(nil),         // 26: qclaogui.generativelanguage.v1beta1.ListChunksRequest
		(*ListChunksResponse)(nil),        // 27: qclaogui.generativelanguage.v1beta1.ListChunksResponse
		(*Corpus)(nil),                    // 28: qclaogui.generativelanguage.v1beta1.Corpus
		(*fieldmaskpb.FieldMask)(nil),     // 29: google.protobuf.FieldMask
		(*MetadataFilter)(nil),            // 30: qclaogui.generativelanguage.v1beta1.MetadataFilter
		(*Chunk)(nil),                     // 31: qclaogui.generativelanguage.v1beta1.Chunk
		(*Document)(nil),                  // 32: qclaogui.generativelanguage.v1beta1.Document
		(*emptypb.Empty)(nil),             // 33: google.protobuf.Empty
	}
)

var file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_depIdxs = []int32{
	28, // 0: qclaogui.generativelanguage.v1beta1.CreateCorpusRequest.corpus:type_name -> qclaogui.generativelanguage.v1beta1.Corpus
	28, // 1: qclaogui.generativelanguage.v1beta1.UpdateCorpusRequest.corpus:type_name -> qclaogui.generativelanguage.v1beta1.Corpus
	29, // 2: qclaogui.generativelanguage.v1beta1.UpdateCorpusRequest.update_mask:type_name -> google.protobuf.FieldMask
	28, // 3: qclaogui.generativelanguage.v1beta1.ListCorporaResponse.corpora:type_name -> qclaogui.generativelanguage.v1beta1.Corpus
	30, // 4: qclaogui.generativelanguage.v1beta1.QueryCorpusRequest.metadata_filters:type_name -> qclaogui.generativelanguage.v1beta1.MetadataFilter
	8,  // 5: qclaogui.generativelanguage.v1beta1.QueryCorpusResponse.relevant_chunks:type_name -> qclaogui.generativelanguage.v1beta1.RelevantChunk
	31, // 6: qclaogui.generativelanguage.v1beta1.RelevantChunk.chunk:type_name -> qclaogui.generativelanguage.v1beta1.Chunk
	32, // 7: qclaogui.generativelanguage.v1beta1.CreateDocumentRequest.document:type_name -> qclaogui.generativelanguage.v1beta1.Document
	32, // 8: qclaogui.generativelanguage.v1beta1.UpdateDocumentRequest.document:type_name -> qclaogui.generativelanguage.v1beta1.Document
	29, // 9: qclaogui.generativelanguage.v1beta1.UpdateDocumentRequest.update_mask:type_name -> google.protobuf.FieldMask
	32, // 10: qclaogui.generativelanguage.v1beta1.ListDocumentsResponse.documents:type_name -> qclaogui.generativelanguage.v1beta1.Document
	30, // 11: qclaogui.generativelanguage.v1beta1.QueryDocumentRequest.metadata_filters:type_name -> qclaogui.generativelanguage.v1beta1.MetadataFilter
	8,  // 12: qclaogui.generativelanguage.v1beta1.QueryDocumentResponse.relevant_chunks:type_name -> qclaogui.generativelanguage.v1beta1.RelevantChunk
	31, // 13: qclaogui.generativelanguage.v1beta1.CreateChunkRequest.chunk:type_name -> qclaogui.generativelanguage.v1beta1.Chunk
	17, // 14: qclaogui.generativelanguage.v1beta1.BatchCreateChunksRequest.requests:type_name -> qclaogui.generativelanguage.v1beta1.CreateChunkRequest
	31, // 15: qclaogui.generativelanguage.v1beta1.BatchCreateChunksResponse.chunks:type_name -> qclaogui.generativelanguage.v1beta1.Chunk
	31, // 16: qclaogui.generativelanguage.v1beta1.UpdateChunkRequest.chunk:type_name -> qclaogui.generativelanguage.v1beta1.Chunk
	29, // 17: qclaogui.generativelanguage.v1beta1.UpdateChunkRequest.update_mask:type_name -> google.protobuf.FieldMask
	21, // 18: qclaogui.generativelanguage.v1beta1.BatchUpdateChunksRequest.requests:type_name -> qclaogui.generativelanguage.v1beta1.UpdateChunkRequest
	31, // 19: qclaogui.generativelanguage.v1beta1.BatchUpdateChunksResponse.chunks:type_name -> qclaogui.generativelanguage.v1beta1.Chunk
	24, // 20: qclaogui.generativelanguage.v1beta1.BatchDeleteChunksRequest.requests:type_name -> qclaogui.generativelanguage.v1beta1.DeleteChunkRequest
	31, // 21: qclaogui.generativelanguage.v1beta1.ListChunksResponse.chunks:type_name -> qclaogui.generativelanguage.v1beta1.Chunk
	0,  // 22: qclaogui.generativelanguage.v1beta1.RetrieverService.CreateCorpus:input_type -> qclaogui.generativelanguage.v1beta1.CreateCorpusRequest
	1,  // 23: qclaogui.generativelanguage.v1beta1.RetrieverService.GetCorpus:input_type -> qclaogui.generativelanguage.v1beta1.GetCorpusRequest
	2,  // 24: qclaogui.generativelanguage.v1beta1.RetrieverService.UpdateCorpus:input_type -> qclaogui.generativelanguage.v1beta1.UpdateCorpusRequest
	3,  // 25: qclaogui.generativelanguage.v1beta1.RetrieverService.DeleteCorpus:input_type -> qclaogui.generativelanguage.v1beta1.DeleteCorpusRequest
	4,  // 26: qclaogui.generativelanguage.v1beta1.RetrieverService.ListCorpora:input_type -> qclaogui.generativelanguage.v1beta1.ListCorporaRequest
	6,  // 27: qclaogui.generativelanguage.v1beta1.RetrieverService.QueryCorpus:input_type -> qclaogui.generativelanguage.v1beta1.QueryCorpusRequest
	9,  // 28: qclaogui.generativelanguage.v1beta1.RetrieverService.CreateDocument:input_type -> qclaogui.generativelanguage.v1beta1.CreateDocumentRequest
	10, // 29: qclaogui.generativelanguage.v1beta1.RetrieverService.GetDocument:input_type -> qclaogui.generativelanguage.v1beta1.GetDocumentRequest
	11, // 30: qclaogui.generativelanguage.v1beta1.RetrieverService.UpdateDocument:input_type -> qclaogui.generativelanguage.v1beta1.UpdateDocumentRequest
	12, // 31: qclaogui.generativelanguage.v1beta1.RetrieverService.DeleteDocument:input_type -> qclaogui.generativelanguage.v1beta1.DeleteDocumentRequest
	13, // 32: qclaogui.generativelanguage.v1beta1.RetrieverService.ListDocuments:input_type -> qclaogui.generativelanguage.v1beta1.ListDocumentsRequest
	15, // 33: qclaogui.generativelanguage.v1beta1.RetrieverService.QueryDocument:input_type -> qclaogui.generativelanguage.v1beta1.QueryDocumentRequest
	17, // 34: qclaogui.generativelanguage.v1beta1.RetrieverService.CreateChunk:input_type -> qclaogui.generativelanguage.v1beta1.CreateChunkRequest
	18, // 35: qclaogui.generativelanguage.v1beta1.RetrieverService.BatchCreateChunks:input_type -> qclaogui.generativelanguage.v1beta1.BatchCreateChunksRequest
	20, // 36: qclaogui.generativelanguage.v1beta1.RetrieverService.GetChunk:input_type -> qclaogui.generativelanguage.v1beta1.GetChunkRequest
	21, // 37: qclaogui.generativelanguage.v1beta1.RetrieverService.UpdateChunk:input_type -> qclaogui.generativelanguage.v1beta1.UpdateChunkRequest
	22, // 38: qclaogui.generativelanguage.v1beta1.RetrieverService.BatchUpdateChunks:input_type -> qclaogui.generativelanguage.v1beta1.BatchUpdateChunksRequest
	24, // 39: qclaogui.generativelanguage.v1beta1.RetrieverService.DeleteChunk:input_type -> qclaogui.generativelanguage.v1beta1.DeleteChunkRequest
	25, // 40: qclaogui.generativelanguage.v1beta1.RetrieverService.BatchDeleteChunks:input_type -> qclaogui.generativelanguage.v1beta1.BatchDeleteChunksRequest
	26, // 41: qclaogui.generativelanguage.v1beta1.RetrieverService.ListChunks:input_type -> qclaogui.generativelanguage.v1beta1.ListChunksRequest
	28, // 42: qclaogui.generativelanguage.v1beta1.RetrieverService.CreateCorpus:output_type -> qclaogui.generativelanguage.v1beta1.Corpus
	28, // 43: qclaogui.generativelanguage.v1beta1.RetrieverService.GetCorpus:output_type -> qclaogui.generativelanguage.v1beta1.Corpus
	28, // 44: qclaogui.generativelanguage.v1beta1.RetrieverService.UpdateCorpus:output_type -> qclaogui.generativelanguage.v1beta1.Corpus
	33, // 45: qclaogui.generativelanguage.v1beta1.RetrieverService.DeleteCorpus:output_type -> google.protobuf.Empty
	5,  // 46: qclaogui.generativelanguage.v1beta1.RetrieverService.ListCorpora:output_type -> qclaogui.generativelanguage.v1beta1.ListCorporaResponse
	7,  // 47: qclaogui.generativelanguage.v1beta1.RetrieverService.QueryCorpus:output_type -> qclaogui.generativelanguage.v1beta1.QueryCorpusResponse
	32, // 48: qclaogui.generativelanguage.v1beta1.RetrieverService.CreateDocument:output_type -> qclaogui.generativelanguage.v1beta1.Document
	32, // 49: qclaogui.generativelanguage.v1beta1.RetrieverService.GetDocument:output_type -> qclaogui.generativelanguage.v1beta1.Document
	32, // 50: qclaogui.generativelanguage.v1beta1.RetrieverService.UpdateDocument:output_type -> qclaogui.generativelanguage.v1beta1.Document
	33, // 51: qclaogui.generativelanguage.v1beta1.RetrieverService.DeleteDocument:output_type -> google.protobuf.Empty
	14, // 52: qclaogui.generativelanguage.v1beta1.RetrieverService.ListDocuments:output_type -> qclaogui.generativelanguage.v1beta1.ListDocumentsResponse
	16, // 53: qclaogui.generativelanguage.v1beta1.RetrieverService.QueryDocument:output_type -> qclaogui.generativelanguage.v1beta1.QueryDocumentResponse
	31, // 54: qclaogui.generativelanguage.v1beta1.RetrieverService.CreateChunk:output_type -> qclaogui.generativelanguage.v1beta1.Chunk
	19, // 55: qclaogui.generativelanguage.v1beta1.RetrieverService.BatchCreateChunks:output_type -> qclaogui.generativelanguage.v1beta1.BatchCreateChunksResponse
	31, // 56: qclaogui.generativelanguage.v1beta1.RetrieverService.GetChunk:output_type -> qclaogui.generativelanguage.v1beta1.Chunk
	31, // 57: qclaogui.generativelanguage.v1beta1.RetrieverService.UpdateChunk:output_type -> qclaogui.generativelanguage.v1beta1.Chunk
	23, // 58: qclaogui.generativelanguage.v1beta1.RetrieverService.BatchUpdateChunks:output_type -> qclaogui.generativelanguage.v1beta1.BatchUpdateChunksResponse
	33, // 59: qclaogui.generativelanguage.v1beta1.RetrieverService.DeleteChunk:output_type -> google.protobuf.Empty
	33, // 60: qclaogui.generativelanguage.v1beta1.RetrieverService.BatchDeleteChunks:output_type -> google.protobuf.Empty
	27, // 61: qclaogui.generativelanguage.v1beta1.RetrieverService.ListChunks:output_type -> qclaogui.generativelanguage.v1beta1.ListChunksResponse
	42, // [42:62] is the sub-list for method output_type
	22, // [22:42] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_init() }
func file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_init() {
	if File_qclaogui_generativelanguage_v1beta1_retriever_service_proto != nil {
		return
	}
	file_qclaogui_generativelanguage_v1beta1_retriever_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDesc), len(file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_goTypes,
		DependencyIndexes: file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_depIdxs,
		MessageInfos:      file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_msgTypes,
	}.Build()
	File_qclaogui_generativelanguage_v1beta1_retriever_service_proto = out.File
	file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_goTypes = nil
	file_qclaogui_generativelanguage_v1beta1_retriever_service_proto_depIdxs = nil
}
