// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: qclaogui/generativelanguage/v1beta/content.proto

package generativelanguagepb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type contains the list of OpenAPI data types as defined by
// https://spec.openapis.org/oas/v3.0.3#data-types
type Type int32

const (
	// Not specified, should not be used.
	Type_TYPE_UNSPECIFIED Type = 0
	// String type.
	Type_STRING Type = 1
	// Number type.
	Type_NUMBER Type = 2
	// Integer type.
	Type_INTEGER Type = 3
	// Boolean type.
	Type_BOOLEAN Type = 4
	// Array type.
	Type_ARRAY Type = 5
	// Object type.
	Type_OBJECT Type = 6
	// Null type.
	// HACK: We use this to handle optional parameters, which users are specifying
	// optional things by using a OneOf with a second type of NULL.
	Type_NULL Type = 7
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "STRING",
		2: "NUMBER",
		3: "INTEGER",
		4: "BOOLEAN",
		5: "ARRAY",
		6: "OBJECT",
		7: "NULL",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"STRING":           1,
		"NUMBER":           2,
		"INTEGER":          3,
		"BOOLEAN":          4,
		"ARRAY":            5,
		"OBJECT":           6,
		"NULL":             7,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{0}
}

// Content Part modality
type Modality int32

const (
	// Unspecified modality.
	Modality_MODALITY_UNSPECIFIED Modality = 0
	// Plain text.
	Modality_TEXT Modality = 1
	// Image.
	Modality_IMAGE Modality = 2
	// Video.
	Modality_VIDEO Modality = 3
	// Audio.
	Modality_AUDIO Modality = 4
	// Document, e.g. PDF.
	Modality_DOCUMENT Modality = 5
)

// Enum value maps for Modality.
var (
	Modality_name = map[int32]string{
		0: "MODALITY_UNSPECIFIED",
		1: "TEXT",
		2: "IMAGE",
		3: "VIDEO",
		4: "AUDIO",
		5: "DOCUMENT",
	}
	Modality_value = map[string]int32{
		"MODALITY_UNSPECIFIED": 0,
		"TEXT":                 1,
		"IMAGE":                2,
		"VIDEO":                3,
		"AUDIO":                4,
		"DOCUMENT":             5,
	}
)

func (x Modality) Enum() *Modality {
	p := new(Modality)
	*p = x
	return p
}

func (x Modality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Modality) Descriptor() protoreflect.EnumDescriptor {
	return file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[1].Descriptor()
}

func (Modality) Type() protoreflect.EnumType {
	return &file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[1]
}

func (x Modality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Modality.Descriptor instead.
func (Modality) EnumDescriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{1}
}

// Supported programming languages for the generated code.
type ExecutableCode_Language int32

const (
	// Unspecified language. This value should not be used.
	ExecutableCode_LANGUAGE_UNSPECIFIED ExecutableCode_Language = 0
	// Python >= 3.10, with numpy and simpy available.
	ExecutableCode_PYTHON ExecutableCode_Language = 1
)

// Enum value maps for ExecutableCode_Language.
var (
	ExecutableCode_Language_name = map[int32]string{
		0: "LANGUAGE_UNSPECIFIED",
		1: "PYTHON",
	}
	ExecutableCode_Language_value = map[string]int32{
		"LANGUAGE_UNSPECIFIED": 0,
		"PYTHON":               1,
	}
)

func (x ExecutableCode_Language) Enum() *ExecutableCode_Language {
	p := new(ExecutableCode_Language)
	*p = x
	return p
}

func (x ExecutableCode_Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutableCode_Language) Descriptor() protoreflect.EnumDescriptor {
	return file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[2].Descriptor()
}

func (ExecutableCode_Language) Type() protoreflect.EnumType {
	return &file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[2]
}

func (x ExecutableCode_Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutableCode_Language.Descriptor instead.
func (ExecutableCode_Language) EnumDescriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{4, 0}
}

// Enumeration of possible outcomes of the code execution.
type CodeExecutionResult_Outcome int32

const (
	// Unspecified status. This value should not be used.
	CodeExecutionResult_OUTCOME_UNSPECIFIED CodeExecutionResult_Outcome = 0
	// Code execution completed successfully.
	CodeExecutionResult_OUTCOME_OK CodeExecutionResult_Outcome = 1
	// Code execution finished but with a failure. `stderr` should contain the
	// reason.
	CodeExecutionResult_OUTCOME_FAILED CodeExecutionResult_Outcome = 2
	// Code execution ran for too long, and was cancelled. There may or may not
	// be a partial output present.
	CodeExecutionResult_OUTCOME_DEADLINE_EXCEEDED CodeExecutionResult_Outcome = 3
)

// Enum value maps for CodeExecutionResult_Outcome.
var (
	CodeExecutionResult_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_OK",
		2: "OUTCOME_FAILED",
		3: "OUTCOME_DEADLINE_EXCEEDED",
	}
	CodeExecutionResult_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":       0,
		"OUTCOME_OK":                1,
		"OUTCOME_FAILED":            2,
		"OUTCOME_DEADLINE_EXCEEDED": 3,
	}
)

func (x CodeExecutionResult_Outcome) Enum() *CodeExecutionResult_Outcome {
	p := new(CodeExecutionResult_Outcome)
	*p = x
	return p
}

func (x CodeExecutionResult_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodeExecutionResult_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[3].Descriptor()
}

func (CodeExecutionResult_Outcome) Type() protoreflect.EnumType {
	return &file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[3]
}

func (x CodeExecutionResult_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodeExecutionResult_Outcome.Descriptor instead.
func (CodeExecutionResult_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{5, 0}
}

// The mode of the predictor to be used in dynamic retrieval.
type DynamicRetrievalConfig_Mode int32

const (
	// Always trigger retrieval.
	DynamicRetrievalConfig_MODE_UNSPECIFIED DynamicRetrievalConfig_Mode = 0
	// Run retrieval only when system decides it is necessary.
	DynamicRetrievalConfig_MODE_DYNAMIC DynamicRetrievalConfig_Mode = 1
)

// Enum value maps for DynamicRetrievalConfig_Mode.
var (
	DynamicRetrievalConfig_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_DYNAMIC",
	}
	DynamicRetrievalConfig_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_DYNAMIC":     1,
	}
)

func (x DynamicRetrievalConfig_Mode) Enum() *DynamicRetrievalConfig_Mode {
	p := new(DynamicRetrievalConfig_Mode)
	*p = x
	return p
}

func (x DynamicRetrievalConfig_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DynamicRetrievalConfig_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[4].Descriptor()
}

func (DynamicRetrievalConfig_Mode) Type() protoreflect.EnumType {
	return &file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[4]
}

func (x DynamicRetrievalConfig_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DynamicRetrievalConfig_Mode.Descriptor instead.
func (DynamicRetrievalConfig_Mode) EnumDescriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{8, 0}
}

// Defines the execution behavior for function calling by defining the
// execution mode.
type FunctionCallingConfig_Mode int32

const (
	// Unspecified function calling mode. This value should not be used.
	FunctionCallingConfig_MODE_UNSPECIFIED FunctionCallingConfig_Mode = 0
	// Default model behavior, model decides to predict either a function call
	// or a natural language response.
	FunctionCallingConfig_AUTO FunctionCallingConfig_Mode = 1
	// Model is constrained to always predicting a function call only.
	// If "allowed_function_names" are set, the predicted function call will be
	// limited to any one of "allowed_function_names", else the predicted
	// function call will be any one of the provided "function_declarations".
	FunctionCallingConfig_ANY FunctionCallingConfig_Mode = 2
	// Model will not predict any function call. Model behavior is same as when
	// not passing any function declarations.
	FunctionCallingConfig_NONE FunctionCallingConfig_Mode = 3
	// Model decides to predict either a function call
	// or a natural language response, but will validate function calls with
	// constrained decoding.
	FunctionCallingConfig_VALIDATED FunctionCallingConfig_Mode = 4
)

// Enum value maps for FunctionCallingConfig_Mode.
var (
	FunctionCallingConfig_Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "AUTO",
		2: "ANY",
		3: "NONE",
		4: "VALIDATED",
	}
	FunctionCallingConfig_Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"AUTO":             1,
		"ANY":              2,
		"NONE":             3,
		"VALIDATED":        4,
	}
)

func (x FunctionCallingConfig_Mode) Enum() *FunctionCallingConfig_Mode {
	p := new(FunctionCallingConfig_Mode)
	*p = x
	return p
}

func (x FunctionCallingConfig_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionCallingConfig_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[5].Descriptor()
}

func (FunctionCallingConfig_Mode) Type() protoreflect.EnumType {
	return &file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes[5]
}

func (x FunctionCallingConfig_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionCallingConfig_Mode.Descriptor instead.
func (FunctionCallingConfig_Mode) EnumDescriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{11, 0}
}

// The base structured datatype containing multi-part content of a message.
//
// A `Content` includes a `role` field designating the producer of the `Content`
// and a `parts` field containing multi-part data that contains the content of
// the message turn.
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered `Parts` that constitute a single message. Parts may have different
	// MIME types.
	Parts []*Part `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	// Optional. The producer of the content. Must be either 'user' or 'model'.
	//
	// Useful to set for multi-turn conversations, otherwise can be left blank
	// or unset.
	Role          string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{0}
}

func (x *Content) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Content) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// A datatype containing media that is part of a multi-part `Content` message.
//
// A `Part` consists of data which has an associated datatype. A `Part` can only
// contain one of the accepted types in `Part.data`.
//
// A `Part` must have a fixed IANA MIME type identifying the type and subtype
// of the media if the `inline_data` field is filled with raw bytes.
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Part_Text
	//	*Part_InlineData
	//	*Part_FunctionCall
	//	*Part_FunctionResponse
	//	*Part_FileData
	//	*Part_ExecutableCode
	//	*Part_CodeExecutionResult
	Data isPart_Data `protobuf_oneof:"data"`
	// Optional. Indicates if the part is thought from the model.
	Thought       bool `protobuf:"varint,11,opt,name=thought,proto3" json:"thought,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{1}
}

func (x *Part) GetData() isPart_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Part) GetText() string {
	if x != nil {
		if x, ok := x.Data.(*Part_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Part) GetInlineData() *Blob {
	if x != nil {
		if x, ok := x.Data.(*Part_InlineData); ok {
			return x.InlineData
		}
	}
	return nil
}

func (x *Part) GetFunctionCall() *FunctionCall {
	if x != nil {
		if x, ok := x.Data.(*Part_FunctionCall); ok {
			return x.FunctionCall
		}
	}
	return nil
}

func (x *Part) GetFunctionResponse() *FunctionResponse {
	if x != nil {
		if x, ok := x.Data.(*Part_FunctionResponse); ok {
			return x.FunctionResponse
		}
	}
	return nil
}

func (x *Part) GetFileData() *FileData {
	if x != nil {
		if x, ok := x.Data.(*Part_FileData); ok {
			return x.FileData
		}
	}
	return nil
}

func (x *Part) GetExecutableCode() *ExecutableCode {
	if x != nil {
		if x, ok := x.Data.(*Part_ExecutableCode); ok {
			return x.ExecutableCode
		}
	}
	return nil
}

func (x *Part) GetCodeExecutionResult() *CodeExecutionResult {
	if x != nil {
		if x, ok := x.Data.(*Part_CodeExecutionResult); ok {
			return x.CodeExecutionResult
		}
	}
	return nil
}

func (x *Part) GetThought() bool {
	if x != nil {
		return x.Thought
	}
	return false
}

type isPart_Data interface {
	isPart_Data()
}

type Part_Text struct {
	// Inline text.
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type Part_InlineData struct {
	// Inline media bytes.
	InlineData *Blob `protobuf:"bytes,3,opt,name=inline_data,json=inlineData,proto3,oneof"`
}

type Part_FunctionCall struct {
	// A predicted `FunctionCall` returned from the model that contains
	// a string representing the `FunctionDeclaration.name` with the
	// arguments and their values.
	FunctionCall *FunctionCall `protobuf:"bytes,4,opt,name=function_call,json=functionCall,proto3,oneof"`
}

type Part_FunctionResponse struct {
	// The result output of a `FunctionCall` that contains a string
	// representing the `FunctionDeclaration.name` and a structured JSON
	// object containing any output from the function is used as context to
	// the model.
	FunctionResponse *FunctionResponse `protobuf:"bytes,5,opt,name=function_response,json=functionResponse,proto3,oneof"`
}

type Part_FileData struct {
	// URI based data.
	FileData *FileData `protobuf:"bytes,6,opt,name=file_data,json=fileData,proto3,oneof"`
}

type Part_ExecutableCode struct {
	// Code generated by the model that is meant to be executed.
	ExecutableCode *ExecutableCode `protobuf:"bytes,9,opt,name=executable_code,json=executableCode,proto3,oneof"`
}

type Part_CodeExecutionResult struct {
	// Result of executing the `ExecutableCode`.
	CodeExecutionResult *CodeExecutionResult `protobuf:"bytes,10,opt,name=code_execution_result,json=codeExecutionResult,proto3,oneof"`
}

func (*Part_Text) isPart_Data() {}

func (*Part_InlineData) isPart_Data() {}

func (*Part_FunctionCall) isPart_Data() {}

func (*Part_FunctionResponse) isPart_Data() {}

func (*Part_FileData) isPart_Data() {}

func (*Part_ExecutableCode) isPart_Data() {}

func (*Part_CodeExecutionResult) isPart_Data() {}

// Raw media bytes.
//
// Text should not be sent as raw bytes, use the 'text' field.
type Blob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IANA standard MIME type of the source data.
	// Examples:
	//   - image/png
	//   - image/jpeg
	//
	// If an unsupported MIME type is provided, an error will be returned. For a
	// complete list of supported types, see [Supported file
	// formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Raw bytes for media formats.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{2}
}

func (x *Blob) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// URI based data.
type FileData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The IANA standard MIME type of the source data.
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Required. URI.
	FileUri       string `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileData) Reset() {
	*x = FileData{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileData) ProtoMessage() {}

func (x *FileData) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileData.ProtoReflect.Descriptor instead.
func (*FileData) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{3}
}

func (x *FileData) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileData) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

// Code generated by the model that is meant to be executed, and the result
// returned to the model.
//
// Only generated when using the `CodeExecution` tool, in which the code will
// be automatically executed, and a corresponding `CodeExecutionResult` will
// also be generated.
type ExecutableCode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Programming language of the `code`.
	Language ExecutableCode_Language `protobuf:"varint,1,opt,name=language,proto3,enum=qclaogui.generativelanguage.v1beta.ExecutableCode_Language" json:"language,omitempty"`
	// Required. The code to be executed.
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutableCode) Reset() {
	*x = ExecutableCode{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutableCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutableCode) ProtoMessage() {}

func (x *ExecutableCode) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutableCode.ProtoReflect.Descriptor instead.
func (*ExecutableCode) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutableCode) GetLanguage() ExecutableCode_Language {
	if x != nil {
		return x.Language
	}
	return ExecutableCode_LANGUAGE_UNSPECIFIED
}

func (x *ExecutableCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Result of executing the `ExecutableCode`.
//
// Only generated when using the `CodeExecution`, and always follows a `part`
// containing the `ExecutableCode`.
type CodeExecutionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Outcome of the code execution.
	Outcome CodeExecutionResult_Outcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=qclaogui.generativelanguage.v1beta.CodeExecutionResult_Outcome" json:"outcome,omitempty"`
	// Optional. Contains stdout when code execution is successful, stderr or
	// other description otherwise.
	Output        string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeExecutionResult) Reset() {
	*x = CodeExecutionResult{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeExecutionResult) ProtoMessage() {}

func (x *CodeExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeExecutionResult.ProtoReflect.Descriptor instead.
func (*CodeExecutionResult) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{5}
}

func (x *CodeExecutionResult) GetOutcome() CodeExecutionResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return CodeExecutionResult_OUTCOME_UNSPECIFIED
}

func (x *CodeExecutionResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// Tool details that the model may use to generate response.
//
// A `Tool` is a piece of code that enables the system to interact with
// external systems to perform an action, or set of actions, outside of
// knowledge and scope of the model.
type Tool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. A list of `FunctionDeclarations` available to the model that can
	// be used for function calling.
	//
	// The model or system does not execute the function. Instead the defined
	// function may be returned as a
	// [FunctionCall][qclaogui.generativelanguage.v1beta.Part.function_call] with
	// arguments to the client side for execution. The model may decide to call a
	// subset of these functions by populating
	// [FunctionCall][qclaogui.generativelanguage.v1beta.Part.function_call] in
	// the response. The next conversation turn may contain a
	// [FunctionResponse][qclaogui.generativelanguage.v1beta.Part.function_response]
	// with the [Content.role][qclaogui.generativelanguage.v1beta.Content.role]
	// "function" generation context for the next model turn.
	FunctionDeclarations []*FunctionDeclaration `protobuf:"bytes,1,rep,name=function_declarations,json=functionDeclarations,proto3" json:"function_declarations,omitempty"`
	// Optional. Retrieval tool that is powered by Google search.
	GoogleSearchRetrieval *GoogleSearchRetrieval `protobuf:"bytes,2,opt,name=google_search_retrieval,json=googleSearchRetrieval,proto3" json:"google_search_retrieval,omitempty"`
	// Optional. Enables the model to execute code as part of generation.
	CodeExecution *CodeExecution `protobuf:"bytes,3,opt,name=code_execution,json=codeExecution,proto3" json:"code_execution,omitempty"`
	// Optional. GoogleSearch tool type.
	// Tool to support Google Search in Model. Powered by Google.
	GoogleSearch  *Tool_GoogleSearch `protobuf:"bytes,4,opt,name=google_search,json=googleSearch,proto3" json:"google_search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{6}
}

func (x *Tool) GetFunctionDeclarations() []*FunctionDeclaration {
	if x != nil {
		return x.FunctionDeclarations
	}
	return nil
}

func (x *Tool) GetGoogleSearchRetrieval() *GoogleSearchRetrieval {
	if x != nil {
		return x.GoogleSearchRetrieval
	}
	return nil
}

func (x *Tool) GetCodeExecution() *CodeExecution {
	if x != nil {
		return x.CodeExecution
	}
	return nil
}

func (x *Tool) GetGoogleSearch() *Tool_GoogleSearch {
	if x != nil {
		return x.GoogleSearch
	}
	return nil
}

// Tool to retrieve public web data for grounding, powered by Google.
type GoogleSearchRetrieval struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifies the dynamic retrieval configuration for the given source.
	DynamicRetrievalConfig *DynamicRetrievalConfig `protobuf:"bytes,1,opt,name=dynamic_retrieval_config,json=dynamicRetrievalConfig,proto3" json:"dynamic_retrieval_config,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GoogleSearchRetrieval) Reset() {
	*x = GoogleSearchRetrieval{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleSearchRetrieval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleSearchRetrieval) ProtoMessage() {}

func (x *GoogleSearchRetrieval) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleSearchRetrieval.ProtoReflect.Descriptor instead.
func (*GoogleSearchRetrieval) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{7}
}

func (x *GoogleSearchRetrieval) GetDynamicRetrievalConfig() *DynamicRetrievalConfig {
	if x != nil {
		return x.DynamicRetrievalConfig
	}
	return nil
}

// Describes the options to customize dynamic retrieval.
type DynamicRetrievalConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mode of the predictor to be used in dynamic retrieval.
	Mode DynamicRetrievalConfig_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=qclaogui.generativelanguage.v1beta.DynamicRetrievalConfig_Mode" json:"mode,omitempty"`
	// The threshold to be used in dynamic retrieval.
	// If not set, a system default value is used.
	DynamicThreshold *float32 `protobuf:"fixed32,2,opt,name=dynamic_threshold,json=dynamicThreshold,proto3,oneof" json:"dynamic_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DynamicRetrievalConfig) Reset() {
	*x = DynamicRetrievalConfig{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicRetrievalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicRetrievalConfig) ProtoMessage() {}

func (x *DynamicRetrievalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicRetrievalConfig.ProtoReflect.Descriptor instead.
func (*DynamicRetrievalConfig) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{8}
}

func (x *DynamicRetrievalConfig) GetMode() DynamicRetrievalConfig_Mode {
	if x != nil {
		return x.Mode
	}
	return DynamicRetrievalConfig_MODE_UNSPECIFIED
}

func (x *DynamicRetrievalConfig) GetDynamicThreshold() float32 {
	if x != nil && x.DynamicThreshold != nil {
		return *x.DynamicThreshold
	}
	return 0
}

// Tool that executes code generated by the model, and automatically returns
// the result to the model.
//
// See also `ExecutableCode` and `CodeExecutionResult` which are only generated
// when using this tool.
type CodeExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeExecution) Reset() {
	*x = CodeExecution{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeExecution) ProtoMessage() {}

func (x *CodeExecution) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeExecution.ProtoReflect.Descriptor instead.
func (*CodeExecution) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{9}
}

// The Tool configuration containing parameters for specifying `Tool` use
// in the request.
type ToolConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Function calling config.
	FunctionCallingConfig *FunctionCallingConfig `protobuf:"bytes,1,opt,name=function_calling_config,json=functionCallingConfig,proto3" json:"function_calling_config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ToolConfig) Reset() {
	*x = ToolConfig{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolConfig) ProtoMessage() {}

func (x *ToolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolConfig.ProtoReflect.Descriptor instead.
func (*ToolConfig) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{10}
}

func (x *ToolConfig) GetFunctionCallingConfig() *FunctionCallingConfig {
	if x != nil {
		return x.FunctionCallingConfig
	}
	return nil
}

// Configuration for specifying function calling behavior.
type FunctionCallingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Specifies the mode in which function calling should execute. If
	// unspecified, the default value will be set to AUTO.
	Mode FunctionCallingConfig_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=qclaogui.generativelanguage.v1beta.FunctionCallingConfig_Mode" json:"mode,omitempty"`
	// Optional. A set of function names that, when provided, limits the functions
	// the model will call.
	//
	// This should only be set when the Mode is ANY. Function names
	// should match [FunctionDeclaration.name]. With mode set to ANY, model will
	// predict a function call from the set of function names provided.
	AllowedFunctionNames []string `protobuf:"bytes,2,rep,name=allowed_function_names,json=allowedFunctionNames,proto3" json:"allowed_function_names,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FunctionCallingConfig) Reset() {
	*x = FunctionCallingConfig{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCallingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCallingConfig) ProtoMessage() {}

func (x *FunctionCallingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCallingConfig.ProtoReflect.Descriptor instead.
func (*FunctionCallingConfig) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{11}
}

func (x *FunctionCallingConfig) GetMode() FunctionCallingConfig_Mode {
	if x != nil {
		return x.Mode
	}
	return FunctionCallingConfig_MODE_UNSPECIFIED
}

func (x *FunctionCallingConfig) GetAllowedFunctionNames() []string {
	if x != nil {
		return x.AllowedFunctionNames
	}
	return nil
}

// Structured representation of a function declaration as defined by the
// [OpenAPI 3.03 specification](https://spec.openapis.org/oas/v3.0.3). Included
// in this declaration are the function name and parameters. This
// FunctionDeclaration is a representation of a block of code that can be used
// as a `Tool` by the model and executed by the client.
type FunctionDeclaration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The name of the function.
	// Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum
	// length of 63.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. A brief description of the function.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Optional. Describes the parameters to this function. Reflects the Open
	// API 3.03 Parameter Object string Key: the name of the parameter. Parameter
	// names are case sensitive. Schema Value: the Schema defining the type used
	// for the parameter.
	Parameters *Schema `protobuf:"bytes,3,opt,name=parameters,proto3,oneof" json:"parameters,omitempty"`
	// Optional. Describes the output from this function in JSON Schema format.
	// Reflects the Open API 3.03 Response Object. The Schema defines the type
	// used for the response value of the function.
	Response      *Schema `protobuf:"bytes,4,opt,name=response,proto3,oneof" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDeclaration) Reset() {
	*x = FunctionDeclaration{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDeclaration) ProtoMessage() {}

func (x *FunctionDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDeclaration.ProtoReflect.Descriptor instead.
func (*FunctionDeclaration) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{12}
}

func (x *FunctionDeclaration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDeclaration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDeclaration) GetParameters() *Schema {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *FunctionDeclaration) GetResponse() *Schema {
	if x != nil {
		return x.Response
	}
	return nil
}

// A predicted `FunctionCall` returned from the model that contains
// a string representing the `FunctionDeclaration.name` with the
// arguments and their values.
type FunctionCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The unique id of the function call. If populated, the client to
	// execute the `function_call` and return the response with the matching `id`.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Required. The name of the function to call.
	// Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum
	// length of 63.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. The function parameters and values in JSON object format.
	Args          *structpb.Struct `protobuf:"bytes,2,opt,name=args,proto3,oneof" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{13}
}

func (x *FunctionCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

// The result output from a `FunctionCall` that contains a string
// representing the `FunctionDeclaration.name` and a structured JSON
// object containing any output from the function is used as context to
// the model. This should contain the result of a`FunctionCall` made
// based on model prediction.
type FunctionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The id of the function call this response is for. Populated by
	// the client to match the corresponding function call `id`.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// Required. The name of the function to call.
	// Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum
	// length of 63.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. The function response in JSON object format.
	Response      *structpb.Struct `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionResponse) Reset() {
	*x = FunctionResponse{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionResponse) ProtoMessage() {}

func (x *FunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionResponse.ProtoReflect.Descriptor instead.
func (*FunctionResponse) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{14}
}

func (x *FunctionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionResponse) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

// The `Schema` object allows the definition of input and output data types.
// These types can be objects, but also primitives and arrays.
// Represents a select subset of an [OpenAPI 3.0 schema
// object](https://spec.openapis.org/oas/v3.0.3#schema).
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Data type.
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=qclaogui.generativelanguage.v1beta.Type" json:"type,omitempty"`
	// Optional. The format of the data. This is used only for primitive
	// datatypes. Supported formats:
	//
	//	for NUMBER type: float, double
	//	for INTEGER type: int32, int64
	//	for STRING type: enum, date-time
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// Optional. The title of the schema.
	Title string `protobuf:"bytes,24,opt,name=title,proto3" json:"title,omitempty"`
	// Optional. A brief description of the parameter. This could contain examples
	// of use. Parameter description may be formatted as Markdown.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Optional. Indicates if the value may be null.
	Nullable bool `protobuf:"varint,4,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// Optional. Possible values of the element of Type.STRING with enum format.
	// For example we can define an Enum Direction as :
	// {type:STRING, format:enum, enum:["EAST", NORTH", "SOUTH", "WEST"]}
	Enum []string `protobuf:"bytes,5,rep,name=enum,proto3" json:"enum,omitempty"`
	// Optional. Schema of the elements of Type.ARRAY.
	Items *Schema `protobuf:"bytes,6,opt,name=items,proto3,oneof" json:"items,omitempty"`
	// Optional. Maximum number of the elements for Type.ARRAY.
	MaxItems int64 `protobuf:"varint,21,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	// Optional. Minimum number of the elements for Type.ARRAY.
	MinItems int64 `protobuf:"varint,22,opt,name=min_items,json=minItems,proto3" json:"min_items,omitempty"`
	// Optional. Properties of Type.OBJECT.
	Properties map[string]*Schema `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional. Required properties of Type.OBJECT.
	Required []string `protobuf:"bytes,8,rep,name=required,proto3" json:"required,omitempty"`
	// Optional. SCHEMA FIELDS FOR TYPE INTEGER and NUMBER
	// Minimum value of the Type.INTEGER and Type.NUMBER
	Minimum *float64 `protobuf:"fixed64,11,opt,name=minimum,proto3,oneof" json:"minimum,omitempty"`
	// Optional. Maximum value of the Type.INTEGER and Type.NUMBER
	Maximum *float64 `protobuf:"fixed64,12,opt,name=maximum,proto3,oneof" json:"maximum,omitempty"`
	// Optional. The value should be validated against any (one or more) of the
	// subschemas in the list.
	AnyOf []*Schema `protobuf:"bytes,18,rep,name=any_of,json=anyOf,proto3" json:"any_of,omitempty"`
	// Optional. The order of the properties.
	// Not a standard field in open api spec. Used to determine the order of the
	// properties in the response.
	PropertyOrdering []string `protobuf:"bytes,23,rep,name=property_ordering,json=propertyOrdering,proto3" json:"property_ordering,omitempty"`
	// Optional. Default value of the field. Per JSON Schema, this field is
	// intended for documentation generators and doesn't affect validation. Thus
	// it's included here and ignored so that developers who send schemas with a
	// `default` field don't get unknown-field errors.
	Default       *structpb.Value `protobuf:"bytes,25,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{15}
}

func (x *Schema) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *Schema) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Schema) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Schema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Schema) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *Schema) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

func (x *Schema) GetItems() *Schema {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Schema) GetMaxItems() int64 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *Schema) GetMinItems() int64 {
	if x != nil {
		return x.MinItems
	}
	return 0
}

func (x *Schema) GetProperties() map[string]*Schema {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Schema) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *Schema) GetMinimum() float64 {
	if x != nil && x.Minimum != nil {
		return *x.Minimum
	}
	return 0
}

func (x *Schema) GetMaximum() float64 {
	if x != nil && x.Maximum != nil {
		return *x.Maximum
	}
	return 0
}

func (x *Schema) GetAnyOf() []*Schema {
	if x != nil {
		return x.AnyOf
	}
	return nil
}

func (x *Schema) GetPropertyOrdering() []string {
	if x != nil {
		return x.PropertyOrdering
	}
	return nil
}

func (x *Schema) GetDefault() *structpb.Value {
	if x != nil {
		return x.Default
	}
	return nil
}

// Passage included inline with a grounding configuration.
type GroundingPassage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the passage for attributing this passage in grounded
	// answers.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Content of the passage.
	Content       *Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundingPassage) Reset() {
	*x = GroundingPassage{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundingPassage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundingPassage) ProtoMessage() {}

func (x *GroundingPassage) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundingPassage.ProtoReflect.Descriptor instead.
func (*GroundingPassage) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{16}
}

func (x *GroundingPassage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroundingPassage) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

// A repeated list of passages.
type GroundingPassages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of passages.
	Passages      []*GroundingPassage `protobuf:"bytes,1,rep,name=passages,proto3" json:"passages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundingPassages) Reset() {
	*x = GroundingPassages{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundingPassages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundingPassages) ProtoMessage() {}

func (x *GroundingPassages) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundingPassages.ProtoReflect.Descriptor instead.
func (*GroundingPassages) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{17}
}

func (x *GroundingPassages) GetPassages() []*GroundingPassage {
	if x != nil {
		return x.Passages
	}
	return nil
}

// Represents token counting info for a single modality.
type ModalityTokenCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The modality associated with this token count.
	Modality Modality `protobuf:"varint,1,opt,name=modality,proto3,enum=qclaogui.generativelanguage.v1beta.Modality" json:"modality,omitempty"`
	// Number of tokens.
	TokenCount    int32 `protobuf:"varint,2,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModalityTokenCount) Reset() {
	*x = ModalityTokenCount{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModalityTokenCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModalityTokenCount) ProtoMessage() {}

func (x *ModalityTokenCount) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModalityTokenCount.ProtoReflect.Descriptor instead.
func (*ModalityTokenCount) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{18}
}

func (x *ModalityTokenCount) GetModality() Modality {
	if x != nil {
		return x.Modality
	}
	return Modality_MODALITY_UNSPECIFIED
}

func (x *ModalityTokenCount) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

// GoogleSearch tool type.
// Tool to support Google Search in Model. Powered by Google.
type Tool_GoogleSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool_GoogleSearch) Reset() {
	*x = Tool_GoogleSearch{}
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool_GoogleSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool_GoogleSearch) ProtoMessage() {}

func (x *Tool_GoogleSearch) ProtoReflect() protoreflect.Message {
	mi := &file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool_GoogleSearch.ProtoReflect.Descriptor instead.
func (*Tool_GoogleSearch) Descriptor() ([]byte, []int) {
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP(), []int{6, 0}
}

var File_qclaogui_generativelanguage_v1beta_content_proto protoreflect.FileDescriptor

const file_qclaogui_generativelanguage_v1beta_content_proto_rawDesc = "" +
	"\n" +
	"0qclaogui/generativelanguage/v1beta/content.proto\x12\"qclaogui.generativelanguage.v1beta\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\"c\n" +
	"\aContent\x12>\n" +
	"\x05parts\x18\x01 \x03(\v2(.qclaogui.generativelanguage.v1beta.PartR\x05parts\x12\x18\n" +
	"\x04role\x18\x02 \x01(\tB\x04\xe2A\x01\x01R\x04role\"\xea\x04\n" +
	"\x04Part\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12K\n" +
	"\vinline_data\x18\x03 \x01(\v2(.qclaogui.generativelanguage.v1beta.BlobH\x00R\n" +
	"inlineData\x12W\n" +
	"\rfunction_call\x18\x04 \x01(\v20.qclaogui.generativelanguage.v1beta.FunctionCallH\x00R\ffunctionCall\x12c\n" +
	"\x11function_response\x18\x05 \x01(\v24.qclaogui.generativelanguage.v1beta.FunctionResponseH\x00R\x10functionResponse\x12K\n" +
	"\tfile_data\x18\x06 \x01(\v2,.qclaogui.generativelanguage.v1beta.FileDataH\x00R\bfileData\x12]\n" +
	"\x0fexecutable_code\x18\t \x01(\v22.qclaogui.generativelanguage.v1beta.ExecutableCodeH\x00R\x0eexecutableCode\x12m\n" +
	"\x15code_execution_result\x18\n" +
	" \x01(\v27.qclaogui.generativelanguage.v1beta.CodeExecutionResultH\x00R\x13codeExecutionResult\x12\x1e\n" +
	"\athought\x18\v \x01(\bB\x04\xe2A\x01\x01R\athoughtB\x06\n" +
	"\x04data\"7\n" +
	"\x04Blob\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"N\n" +
	"\bFileData\x12!\n" +
	"\tmime_type\x18\x01 \x01(\tB\x04\xe2A\x01\x01R\bmimeType\x12\x1f\n" +
	"\bfile_uri\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\afileUri\"\xbb\x01\n" +
	"\x0eExecutableCode\x12]\n" +
	"\blanguage\x18\x01 \x01(\x0e2;.qclaogui.generativelanguage.v1beta.ExecutableCode.LanguageB\x04\xe2A\x01\x02R\blanguage\x12\x18\n" +
	"\x04code\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\x04code\"0\n" +
	"\bLanguage\x12\x18\n" +
	"\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PYTHON\x10\x01\"\xfb\x01\n" +
	"\x13CodeExecutionResult\x12_\n" +
	"\aoutcome\x18\x01 \x01(\x0e2?.qclaogui.generativelanguage.v1beta.CodeExecutionResult.OutcomeB\x04\xe2A\x01\x02R\aoutcome\x12\x1c\n" +
	"\x06output\x18\x02 \x01(\tB\x04\xe2A\x01\x01R\x06output\"e\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"OUTCOME_OK\x10\x01\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x02\x12\x1d\n" +
	"\x19OUTCOME_DEADLINE_EXCEEDED\x10\x03\"\xc5\x03\n" +
	"\x04Tool\x12r\n" +
	"\x15function_declarations\x18\x01 \x03(\v27.qclaogui.generativelanguage.v1beta.FunctionDeclarationB\x04\xe2A\x01\x01R\x14functionDeclarations\x12w\n" +
	"\x17google_search_retrieval\x18\x02 \x01(\v29.qclaogui.generativelanguage.v1beta.GoogleSearchRetrievalB\x04\xe2A\x01\x01R\x15googleSearchRetrieval\x12^\n" +
	"\x0ecode_execution\x18\x03 \x01(\v21.qclaogui.generativelanguage.v1beta.CodeExecutionB\x04\xe2A\x01\x01R\rcodeExecution\x12`\n" +
	"\rgoogle_search\x18\x04 \x01(\v25.qclaogui.generativelanguage.v1beta.Tool.GoogleSearchB\x04\xe2A\x01\x01R\fgoogleSearch\x1a\x0e\n" +
	"\fGoogleSearch\"\x8d\x01\n" +
	"\x15GoogleSearchRetrieval\x12t\n" +
	"\x18dynamic_retrieval_config\x18\x01 \x01(\v2:.qclaogui.generativelanguage.v1beta.DynamicRetrievalConfigR\x16dynamicRetrievalConfig\"\xe5\x01\n" +
	"\x16DynamicRetrievalConfig\x12S\n" +
	"\x04mode\x18\x01 \x01(\x0e2?.qclaogui.generativelanguage.v1beta.DynamicRetrievalConfig.ModeR\x04mode\x120\n" +
	"\x11dynamic_threshold\x18\x02 \x01(\x02H\x00R\x10dynamicThreshold\x88\x01\x01\".\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fMODE_DYNAMIC\x10\x01B\x14\n" +
	"\x12_dynamic_threshold\"\x0f\n" +
	"\rCodeExecution\"\x85\x01\n" +
	"\n" +
	"ToolConfig\x12w\n" +
	"\x17function_calling_config\x18\x01 \x01(\v29.qclaogui.generativelanguage.v1beta.FunctionCallingConfigB\x04\xe2A\x01\x01R\x15functionCallingConfig\"\xf7\x01\n" +
	"\x15FunctionCallingConfig\x12X\n" +
	"\x04mode\x18\x01 \x01(\x0e2>.qclaogui.generativelanguage.v1beta.FunctionCallingConfig.ModeB\x04\xe2A\x01\x01R\x04mode\x12:\n" +
	"\x16allowed_function_names\x18\x02 \x03(\tB\x04\xe2A\x01\x01R\x14allowedFunctionNames\"H\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04AUTO\x10\x01\x12\a\n" +
	"\x03ANY\x10\x02\x12\b\n" +
	"\x04NONE\x10\x03\x12\r\n" +
	"\tVALIDATED\x10\x04\"\x9d\x02\n" +
	"\x13FunctionDeclaration\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12&\n" +
	"\vdescription\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vdescription\x12U\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2*.qclaogui.generativelanguage.v1beta.SchemaB\x04\xe2A\x01\x01H\x00R\n" +
	"parameters\x88\x01\x01\x12Q\n" +
	"\bresponse\x18\x04 \x01(\v2*.qclaogui.generativelanguage.v1beta.SchemaB\x04\xe2A\x01\x01H\x01R\bresponse\x88\x01\x01B\r\n" +
	"\v_parametersB\v\n" +
	"\t_response\"\x7f\n" +
	"\fFunctionCall\x12\x14\n" +
	"\x02id\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\x02id\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x126\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructB\x04\xe2A\x01\x01H\x00R\x04args\x88\x01\x01B\a\n" +
	"\x05_args\"}\n" +
	"\x10FunctionResponse\x12\x14\n" +
	"\x02id\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\x02id\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x129\n" +
	"\bresponse\x18\x02 \x01(\v2\x17.google.protobuf.StructB\x04\xe2A\x01\x02R\bresponse\"\x8c\a\n" +
	"\x06Schema\x12B\n" +
	"\x04type\x18\x01 \x01(\x0e2(.qclaogui.generativelanguage.v1beta.TypeB\x04\xe2A\x01\x02R\x04type\x12\x1c\n" +
	"\x06format\x18\x02 \x01(\tB\x04\xe2A\x01\x01R\x06format\x12\x1a\n" +
	"\x05title\x18\x18 \x01(\tB\x04\xe2A\x01\x01R\x05title\x12&\n" +
	"\vdescription\x18\x03 \x01(\tB\x04\xe2A\x01\x01R\vdescription\x12 \n" +
	"\bnullable\x18\x04 \x01(\bB\x04\xe2A\x01\x01R\bnullable\x12\x18\n" +
	"\x04enum\x18\x05 \x03(\tB\x04\xe2A\x01\x01R\x04enum\x12K\n" +
	"\x05items\x18\x06 \x01(\v2*.qclaogui.generativelanguage.v1beta.SchemaB\x04\xe2A\x01\x01H\x00R\x05items\x88\x01\x01\x12!\n" +
	"\tmax_items\x18\x15 \x01(\x03B\x04\xe2A\x01\x01R\bmaxItems\x12!\n" +
	"\tmin_items\x18\x16 \x01(\x03B\x04\xe2A\x01\x01R\bminItems\x12`\n" +
	"\n" +
	"properties\x18\a \x03(\v2:.qclaogui.generativelanguage.v1beta.Schema.PropertiesEntryB\x04\xe2A\x01\x01R\n" +
	"properties\x12 \n" +
	"\brequired\x18\b \x03(\tB\x04\xe2A\x01\x01R\brequired\x12#\n" +
	"\aminimum\x18\v \x01(\x01B\x04\xe2A\x01\x01H\x01R\aminimum\x88\x01\x01\x12#\n" +
	"\amaximum\x18\f \x01(\x01B\x04\xe2A\x01\x01H\x02R\amaximum\x88\x01\x01\x12G\n" +
	"\x06any_of\x18\x12 \x03(\v2*.qclaogui.generativelanguage.v1beta.SchemaB\x04\xe2A\x01\x01R\x05anyOf\x121\n" +
	"\x11property_ordering\x18\x17 \x03(\tB\x04\xe2A\x01\x01R\x10propertyOrdering\x126\n" +
	"\adefault\x18\x19 \x01(\v2\x16.google.protobuf.ValueB\x04\xe2A\x01\x01R\adefault\x1ai\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.qclaogui.generativelanguage.v1beta.SchemaR\x05value:\x028\x01B\b\n" +
	"\x06_itemsB\n" +
	"\n" +
	"\b_minimumB\n" +
	"\n" +
	"\b_maximum\"i\n" +
	"\x10GroundingPassage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\acontent\x18\x02 \x01(\v2+.qclaogui.generativelanguage.v1beta.ContentR\acontent\"e\n" +
	"\x11GroundingPassages\x12P\n" +
	"\bpassages\x18\x01 \x03(\v24.qclaogui.generativelanguage.v1beta.GroundingPassageR\bpassages\"\x7f\n" +
	"\x12ModalityTokenCount\x12H\n" +
	"\bmodality\x18\x01 \x01(\x0e2,.qclaogui.generativelanguage.v1beta.ModalityR\bmodality\x12\x1f\n" +
	"\vtoken_count\x18\x02 \x01(\x05R\n" +
	"tokenCount*o\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STRING\x10\x01\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x02\x12\v\n" +
	"\aINTEGER\x10\x03\x12\v\n" +
	"\aBOOLEAN\x10\x04\x12\t\n" +
	"\x05ARRAY\x10\x05\x12\n" +
	"\n" +
	"\x06OBJECT\x10\x06\x12\b\n" +
	"\x04NULL\x10\a*]\n" +
	"\bModality\x12\x18\n" +
	"\x14MODALITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\t\n" +
	"\x05IMAGE\x10\x02\x12\t\n" +
	"\x05VIDEO\x10\x03\x12\t\n" +
	"\x05AUDIO\x10\x04\x12\f\n" +
	"\bDOCUMENT\x10\x05BUZSgithub.com/qclaogui/gaip/genproto/generativelanguage/apiv1beta/generativelanguagepbb\x06proto3"

var (
	file_qclaogui_generativelanguage_v1beta_content_proto_rawDescOnce sync.Once
	file_qclaogui_generativelanguage_v1beta_content_proto_rawDescData []byte
)

func file_qclaogui_generativelanguage_v1beta_content_proto_rawDescGZIP() []byte {
	file_qclaogui_generativelanguage_v1beta_content_proto_rawDescOnce.Do(func() {
		file_qclaogui_generativelanguage_v1beta_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qclaogui_generativelanguage_v1beta_content_proto_rawDesc), len(file_qclaogui_generativelanguage_v1beta_content_proto_rawDesc)))
	})
	return file_qclaogui_generativelanguage_v1beta_content_proto_rawDescData
}

var (
	file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
	file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes  = make([]protoimpl.MessageInfo, 21)
	file_qclaogui_generativelanguage_v1beta_content_proto_goTypes   = []any{
		(Type)(0),                        // 0: qclaogui.generativelanguage.v1beta.Type
		(Modality)(0),                    // 1: qclaogui.generativelanguage.v1beta.Modality
		(ExecutableCode_Language)(0),     // 2: qclaogui.generativelanguage.v1beta.ExecutableCode.Language
		(CodeExecutionResult_Outcome)(0), // 3: qclaogui.generativelanguage.v1beta.CodeExecutionResult.Outcome
		(DynamicRetrievalConfig_Mode)(0), // 4: qclaogui.generativelanguage.v1beta.DynamicRetrievalConfig.Mode
		(FunctionCallingConfig_Mode)(0),  // 5: qclaogui.generativelanguage.v1beta.FunctionCallingConfig.Mode
		(*Content)(nil),                  // 6: qclaogui.generativelanguage.v1beta.Content
		(*Part)(nil),                     // 7: qclaogui.generativelanguage.v1beta.Part
		(*Blob)(nil),                     // 8: qclaogui.generativelanguage.v1beta.Blob
		(*FileData)(nil),                 // 9: qclaogui.generativelanguage.v1beta.FileData
		(*ExecutableCode)(nil),           // 10: qclaogui.generativelanguage.v1beta.ExecutableCode
		(*CodeExecutionResult)(nil),      // 11: qclaogui.generativelanguage.v1beta.CodeExecutionResult
		(*Tool)(nil),                     // 12: qclaogui.generativelanguage.v1beta.Tool
		(*GoogleSearchRetrieval)(nil),    // 13: qclaogui.generativelanguage.v1beta.GoogleSearchRetrieval
		(*DynamicRetrievalConfig)(nil),   // 14: qclaogui.generativelanguage.v1beta.DynamicRetrievalConfig
		(*CodeExecution)(nil),            // 15: qclaogui.generativelanguage.v1beta.CodeExecution
		(*ToolConfig)(nil),               // 16: qclaogui.generativelanguage.v1beta.ToolConfig
		(*FunctionCallingConfig)(nil),    // 17: qclaogui.generativelanguage.v1beta.FunctionCallingConfig
		(*FunctionDeclaration)(nil),      // 18: qclaogui.generativelanguage.v1beta.FunctionDeclaration
		(*FunctionCall)(nil),             // 19: qclaogui.generativelanguage.v1beta.FunctionCall
		(*FunctionResponse)(nil),         // 20: qclaogui.generativelanguage.v1beta.FunctionResponse
		(*Schema)(nil),                   // 21: qclaogui.generativelanguage.v1beta.Schema
		(*GroundingPassage)(nil),         // 22: qclaogui.generativelanguage.v1beta.GroundingPassage
		(*GroundingPassages)(nil),        // 23: qclaogui.generativelanguage.v1beta.GroundingPassages
		(*ModalityTokenCount)(nil),       // 24: qclaogui.generativelanguage.v1beta.ModalityTokenCount
		(*Tool_GoogleSearch)(nil),        // 25: qclaogui.generativelanguage.v1beta.Tool.GoogleSearch
		nil,                              // 26: qclaogui.generativelanguage.v1beta.Schema.PropertiesEntry
		(*structpb.Struct)(nil),          // 27: google.protobuf.Struct
		(*structpb.Value)(nil),           // 28: google.protobuf.Value
	}
)

var file_qclaogui_generativelanguage_v1beta_content_proto_depIdxs = []int32{
	7,  // 0: qclaogui.generativelanguage.v1beta.Content.parts:type_name -> qclaogui.generativelanguage.v1beta.Part
	8,  // 1: qclaogui.generativelanguage.v1beta.Part.inline_data:type_name -> qclaogui.generativelanguage.v1beta.Blob
	19, // 2: qclaogui.generativelanguage.v1beta.Part.function_call:type_name -> qclaogui.generativelanguage.v1beta.FunctionCall
	20, // 3: qclaogui.generativelanguage.v1beta.Part.function_response:type_name -> qclaogui.generativelanguage.v1beta.FunctionResponse
	9,  // 4: qclaogui.generativelanguage.v1beta.Part.file_data:type_name -> qclaogui.generativelanguage.v1beta.FileData
	10, // 5: qclaogui.generativelanguage.v1beta.Part.executable_code:type_name -> qclaogui.generativelanguage.v1beta.ExecutableCode
	11, // 6: qclaogui.generativelanguage.v1beta.Part.code_execution_result:type_name -> qclaogui.generativelanguage.v1beta.CodeExecutionResult
	2,  // 7: qclaogui.generativelanguage.v1beta.ExecutableCode.language:type_name -> qclaogui.generativelanguage.v1beta.ExecutableCode.Language
	3,  // 8: qclaogui.generativelanguage.v1beta.CodeExecutionResult.outcome:type_name -> qclaogui.generativelanguage.v1beta.CodeExecutionResult.Outcome
	18, // 9: qclaogui.generativelanguage.v1beta.Tool.function_declarations:type_name -> qclaogui.generativelanguage.v1beta.FunctionDeclaration
	13, // 10: qclaogui.generativelanguage.v1beta.Tool.google_search_retrieval:type_name -> qclaogui.generativelanguage.v1beta.GoogleSearchRetrieval
	15, // 11: qclaogui.generativelanguage.v1beta.Tool.code_execution:type_name -> qclaogui.generativelanguage.v1beta.CodeExecution
	25, // 12: qclaogui.generativelanguage.v1beta.Tool.google_search:type_name -> qclaogui.generativelanguage.v1beta.Tool.GoogleSearch
	14, // 13: qclaogui.generativelanguage.v1beta.GoogleSearchRetrieval.dynamic_retrieval_config:type_name -> qclaogui.generativelanguage.v1beta.DynamicRetrievalConfig
	4,  // 14: qclaogui.generativelanguage.v1beta.DynamicRetrievalConfig.mode:type_name -> qclaogui.generativelanguage.v1beta.DynamicRetrievalConfig.Mode
	17, // 15: qclaogui.generativelanguage.v1beta.ToolConfig.function_calling_config:type_name -> qclaogui.generativelanguage.v1beta.FunctionCallingConfig
	5,  // 16: qclaogui.generativelanguage.v1beta.FunctionCallingConfig.mode:type_name -> qclaogui.generativelanguage.v1beta.FunctionCallingConfig.Mode
	21, // 17: qclaogui.generativelanguage.v1beta.FunctionDeclaration.parameters:type_name -> qclaogui.generativelanguage.v1beta.Schema
	21, // 18: qclaogui.generativelanguage.v1beta.FunctionDeclaration.response:type_name -> qclaogui.generativelanguage.v1beta.Schema
	27, // 19: qclaogui.generativelanguage.v1beta.FunctionCall.args:type_name -> google.protobuf.Struct
	27, // 20: qclaogui.generativelanguage.v1beta.FunctionResponse.response:type_name -> google.protobuf.Struct
	0,  // 21: qclaogui.generativelanguage.v1beta.Schema.type:type_name -> qclaogui.generativelanguage.v1beta.Type
	21, // 22: qclaogui.generativelanguage.v1beta.Schema.items:type_name -> qclaogui.generativelanguage.v1beta.Schema
	26, // 23: qclaogui.generativelanguage.v1beta.Schema.properties:type_name -> qclaogui.generativelanguage.v1beta.Schema.PropertiesEntry
	21, // 24: qclaogui.generativelanguage.v1beta.Schema.any_of:type_name -> qclaogui.generativelanguage.v1beta.Schema
	28, // 25: qclaogui.generativelanguage.v1beta.Schema.default:type_name -> google.protobuf.Value
	6,  // 26: qclaogui.generativelanguage.v1beta.GroundingPassage.content:type_name -> qclaogui.generativelanguage.v1beta.Content
	22, // 27: qclaogui.generativelanguage.v1beta.GroundingPassages.passages:type_name -> qclaogui.generativelanguage.v1beta.GroundingPassage
	1,  // 28: qclaogui.generativelanguage.v1beta.ModalityTokenCount.modality:type_name -> qclaogui.generativelanguage.v1beta.Modality
	21, // 29: qclaogui.generativelanguage.v1beta.Schema.PropertiesEntry.value:type_name -> qclaogui.generativelanguage.v1beta.Schema
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_qclaogui_generativelanguage_v1beta_content_proto_init() }
func file_qclaogui_generativelanguage_v1beta_content_proto_init() {
	if File_qclaogui_generativelanguage_v1beta_content_proto != nil {
		return
	}
	file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[1].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_InlineData)(nil),
		(*Part_FunctionCall)(nil),
		(*Part_FunctionResponse)(nil),
		(*Part_FileData)(nil),
		(*Part_ExecutableCode)(nil),
		(*Part_CodeExecutionResult)(nil),
	}
	file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[8].OneofWrappers = []any{}
	file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[12].OneofWrappers = []any{}
	file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[13].OneofWrappers = []any{}
	file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qclaogui_generativelanguage_v1beta_content_proto_rawDesc), len(file_qclaogui_generativelanguage_v1beta_content_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qclaogui_generativelanguage_v1beta_content_proto_goTypes,
		DependencyIndexes: file_qclaogui_generativelanguage_v1beta_content_proto_depIdxs,
		EnumInfos:         file_qclaogui_generativelanguage_v1beta_content_proto_enumTypes,
		MessageInfos:      file_qclaogui_generativelanguage_v1beta_content_proto_msgTypes,
	}.Build()
	File_qclaogui_generativelanguage_v1beta_content_proto = out.File
	file_qclaogui_generativelanguage_v1beta_content_proto_goTypes = nil
	file_qclaogui_generativelanguage_v1beta_content_proto_depIdxs = nil
}
