# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: ci

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '**.go'
      - '!pkg/version/release.go'
      - go.mod
      - go.sum
  pull_request:
    paths:
      - '**.go'
      - '!pkg/version/release.go'
      - go.mod
      - go.sum

permissions:
  contents: read
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true

      - name: Run lint
        run: GOLANGCI_LINT=$(which golangci-lint) GORELEASER=$(which goreleaser) make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Run test
        run: make test