# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: ci

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '**.go'
      - '!pkg/version/release.go'
      - go.mod
      - go.sum
  pull_request:
    paths:
      - '**.go'
      - '!pkg/version/release.go'
      - go.mod
      - go.sum

permissions:
  contents: read
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install golangci-lint
        run: |
          wget -q https://github.com/golangci/golangci-lint/releases/download/v1.55.2/golangci-lint-1.55.2-linux-amd64.tar.gz
          tar -xzf golangci-lint-1.55.2-linux-amd64.tar.gz
          mv golangci-lint-1.55.2-linux-amd64/golangci-lint /home/runner/go/bin/golangci-lint-v1.55.2

      - name: Install GoReleaser
        run: |
          wget -q https://github.com/goreleaser/goreleaser/releases/download/v1.22.1/goreleaser_Linux_x86_64.tar.gz
          tar -xzf goreleaser_Linux_x86_64.tar.gz
          mv goreleaser /home/runner/go/bin/goreleaser-v1.22.1
  
      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Run test
        run: make test