# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: ci

env:
  GOLANGCI_LINT_VERSION: '1.56.0'
  GORELEASER_VERSION: '1.24.0'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '**.go'
      - '!pkg/version/release.go'
      - go.mod
      - go.sum
  pull_request:
    paths:
      - '**.go'
      - '!pkg/version/release.go'
      - go.mod
      - go.sum
  workflow_dispatch: {}

permissions:
  contents: read
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Install golangci-lint
        run: |
          wget -q https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz
          tar -xzf golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz
          mv golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64/golangci-lint /home/runner/go/bin/golangci-lint-v${GOLANGCI_LINT_VERSION}

      - name: Install GoReleaser
        run: |
          wget -q https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_Linux_x86_64.tar.gz
          tar -xzf goreleaser_Linux_x86_64.tar.gz
          mv goreleaser /home/runner/go/bin/goreleaser-v${GORELEASER_VERSION}
  
      - name: Run lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Run test
        run: make test