name: GoReleaser Publish Release

on:
  workflow_call:
    inputs:
      isPreRelease:
        required: true
        type: boolean
    secrets:
      ghPAT:
        required: true
      dhUsername:
        required: true
      dhPassword:
        required: true

jobs:
  publish_release:
    name: ${{ inputs.isPreRelease && 'prerelease' || 'release' }} publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - 
        name: Set variables
        id: vars
        run: |
          if [ -z "${GITHUB_REF_NAME}" ] || [ "${GITHUB_REF_TYPE}" != "tag" ] ; then
            echo "Expected a tag push event, skipping release workflow"
            exit 1
          fi

          tag_name=${GITHUB_REF_NAME}
          echo "GORELEASER_CURRENT_TAG=v${tag_name}" >> $GITHUB_ENV
          echo "RELEASE_DESCRIPTION=${tag_name}" >> $GITHUB_ENV

          RELEASE_NOTES_FILE="docs/release_notes/${tag_name/-rc.*}.md"
          echo "RELEASE_NOTES_FILE=${RELEASE_NOTES_FILE}" >> $GITHUB_ENV
          if [ ! -f "${RELEASE_NOTES_FILE}" ]; then
              echo "Release notes ${RELEASE_NOTES_FILE} not found. Exiting..."
              exit 1
          fi

          echo "RELEASE_BUILD=1" >> $GITHUB_ENV
          # Update version to release-candidate
          echo "PRE_RELEASE_ID=${tag_name#*-}" >> $GITHUB_OUTPUT

          cat .github/.goreleaser.yml .github/.goreleaser.ko.yml > .github/.goreleaser.combined.yml
      - 
        name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dhUsername }}
          password: ${{ secrets.dhPassword }}
      - 
        name: GoReleaser Release
        if: ${{ !inputs.isPreRelease }}
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 #v6.0.0
        with:
          version: v1.24.0
          args: release --clean --timeout 60m --skip=validate --config=.github/.goreleaser.combined.yml  --release-notes="${{env.RELEASE_NOTES_FILE}}"
        env:
          GITHUB_TOKEN: ${{ secrets.ghPAT }}
          PRE_RELEASE_ID: 
      - 
        name: GoReleaser Release Candidate
        if: ${{ inputs.isPreRelease }}
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 #v6.0.0
        with:
          version: v1.24.0
          args: release --clean --timeout 60m --skip=validate --config=.github/.goreleaser.yml --release-notes="${{env.RELEASE_NOTES_FILE}}"
        env:
          GITHUB_TOKEN: ${{ secrets.ghPAT }}
          PRE_RELEASE_ID: ${{steps.vars.outputs.PRE_RELEASE_ID}}
