name: Publish Release
run-name: Publish Release by @${{ github.actor }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  publish-release:
    name: Publish Release
    uses: ./.github/workflows/publish.yml
    with:
      isReleaseCandidate: false
      name: release
    secrets:
      inputToken: ${{ secrets.QCBOT_TOKEN }}