name: GoReleaser Publish Release

on:
  workflow_call:
    inputs:
      isPreRelease:
        required: true
        type: boolean
    secrets:
      ghPAT:
        required: true
      dhUsername:
        required: true
      dhPassword:
        required: true

env:
  GORELEASER_VERSION: '1.24.0'

# permissions:
#   contents: read
#   packages: write # needed for ghcr access

jobs:
  publish_release:
    name: ${{ inputs.isPreRelease && 'prerelease' || 'release' }} publishing
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - 
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - 
        name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dhUsername }}
          password: ${{ secrets.dhPassword }}
      - 
        name: Install GoReleaser
        run: |
          wget -q https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_Linux_x86_64.tar.gz
          tar -xzf goreleaser_Linux_x86_64.tar.gz
          mv goreleaser /home/runner/go/bin/goreleaser-v${GORELEASER_VERSION}
  
      - if: ${{ !inputs.isPreRelease }}
        run: ./tools/scripts/do-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ghPAT }}

      - if: ${{ inputs.isPreRelease }}
        run: ./tools/scripts/do-release-candidate.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ghPAT }}
