name: Publish (workflow call)

# https://docs.github.com/zh/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
on:
  workflow_call:
    inputs:
      isReleaseCandidate:
        required: true
        type: boolean
      name:
        required: true
        type: string
    secrets:
      ghPAT:
        required: true
      dhUsername:
        required: true
      dhPassword:
        required: true

permissions:
  contents: read
  packages: write # needed for ghcr access
        
jobs:

  publish-release:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.dhUsername }}
          password: ${{ secrets.dhPassword }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
  
      - name: Publish release
        if: ${{ !inputs.isReleaseCandidate }}
        env:
          GITHUB_TOKEN: ${{ secrets.ghPAT }}
        run: ./tools/scripts/do-release.sh

      - name: Publish release candidate
        if: ${{ inputs.isReleaseCandidate }}
        env:
          GITHUB_TOKEN: ${{ secrets.ghPAT }}
        run: ./tools/scripts/do-release-candidate.sh