name: Publish Release Candidate
run-name: Publish Release Candidate by @${{ github.actor }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]'

jobs:
  
  publish-release-candidate:
    name: Publish Release Candidate
    uses: ./.github/workflows/publish.yml
    with:
      isReleaseCandidate: true
      name: prerelease
    secrets:
      ghPAT: ${{ secrets.QCBOT_TOKEN }}