name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  check_tag:
    name: Parse the pushed tag version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Set output
        id: vars
        run: |
          case ${GITHUB_REF#refs/*/} in 
            *-rc.*)
              echo 'isRc=true' >> $GITHUB_OUTPUT
              ;;
            *)
              echo 'isRc=false' >> $GITHUB_OUTPUT
              ;;
          esac
    outputs:
      isPreRelease: ${{ steps.vars.outputs.isRc }}

  update_release:
    name: Trigger a release update
    uses: ./.github/workflows/publish-release.yml
    needs: [check_tag]
    with:
      isPreRelease: ${{ needs.check_tag.outputs.isPreRelease == 'true' }}
    secrets:
      ghPAT: ${{ secrets.QCBOT_TOKEN }}
      dhUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dhPassword: ${{ secrets.DOCKERHUB_TOKEN }}
